/* This file was generated by SableCC (http://www.sablecc.org/). */

package ddlgrammar.lexer;

import java.io.*;
import ddlgrammar.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumber(text, line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLPar(line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRPar(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComma(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSemicolon(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCreate(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTable(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIf(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TExists(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInteger(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBigint(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFloat(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTimestamp(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVarchar(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TConstraint(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TForeign(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPrimary(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKey(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TUnique(line, pos); }
    Token new19(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNot(text, line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNull(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReferences(line, pos); }
    Token new22(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBlank(text, line, pos); }
    Token new23(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdentifier(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {40, 40, 5}, {41, 41, 6}, {44, 44, 7}, {48, 57, 8}, {59, 59, 9}, {65, 66, 10}, {67, 67, 11}, {68, 68, 10}, {69, 69, 12}, {70, 72, 10}, {73, 73, 13}, {74, 77, 10}, {78, 78, 14}, {79, 83, 10}, {84, 84, 15}, {85, 90, 10}, {97, 97, 10}, {98, 98, 16}, {99, 99, 17}, {100, 101, 10}, {102, 102, 18}, {103, 104, 10}, {105, 105, 19}, {106, 106, 10}, {107, 107, 20}, {108, 109, 10}, {110, 110, 21}, {111, 111, 10}, {112, 112, 22}, {113, 113, 10}, {114, 114, 23}, {115, 115, 10}, {116, 116, 24}, {117, 117, 25}, {118, 118, 26}, {119, 122, 10}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {},
            {},
            {},
            {{48, 57, 8}, },
            {},
            {{36, 36, 27}, {48, 57, 28}, {65, 90, 29}, {95, 95, 30}, {97, 122, 29}, },
            {{36, 57, -12}, {65, 81, 29}, {82, 82, 31}, {83, 90, 29}, {95, 122, -12}, },
            {{36, 57, -12}, {65, 87, 29}, {88, 88, 32}, {89, 90, 29}, {95, 122, -12}, },
            {{36, 57, -12}, {65, 69, 29}, {70, 70, 33}, {71, 90, 29}, {95, 122, -12}, },
            {{36, 57, -12}, {65, 78, 29}, {79, 79, 34}, {80, 90, 29}, {95, 122, -12}, },
            {{36, 57, -12}, {65, 65, 35}, {66, 90, 29}, {95, 122, -12}, },
            {{36, 95, -12}, {97, 104, 29}, {105, 105, 36}, {106, 122, 29}, },
            {{36, 95, -12}, {97, 110, 29}, {111, 111, 37}, {112, 122, 29}, },
            {{36, 95, -12}, {97, 107, 29}, {108, 108, 38}, {109, 110, 29}, {111, 111, 39}, {112, 122, 29}, },
            {{36, 95, -12}, {97, 109, 29}, {110, 110, 40}, {111, 122, 29}, },
            {{36, 95, -12}, {97, 100, 29}, {101, 101, 41}, {102, 122, 29}, },
            {{36, 110, -19}, {111, 111, 42}, {112, 116, 29}, {117, 117, 43}, {118, 122, 29}, },
            {{36, 95, -12}, {97, 113, 29}, {114, 114, 44}, {115, 122, 29}, },
            {{36, 100, -22}, {101, 101, 45}, {102, 122, 29}, },
            {{36, 104, -18}, {105, 105, 46}, {106, 122, 29}, },
            {{36, 109, -21}, {110, 110, 47}, {111, 122, 29}, },
            {{36, 95, -12}, {97, 97, 48}, {98, 122, 29}, },
            {{36, 122, -12}, },
            {{36, 122, -12}, },
            {{36, 122, -12}, },
            {{36, 122, -12}, },
            {{36, 57, -12}, {65, 68, 29}, {69, 69, 49}, {70, 90, 29}, {95, 122, -12}, },
            {{36, 57, -12}, {65, 72, 29}, {73, 73, 50}, {74, 90, 29}, {95, 122, -12}, },
            {{36, 122, -12}, },
            {{36, 57, -12}, {65, 83, 29}, {84, 84, 51}, {85, 90, 29}, {95, 122, -12}, },
            {{36, 57, -12}, {65, 65, 29}, {66, 66, 52}, {67, 90, 29}, {95, 122, -12}, },
            {{36, 95, -12}, {97, 102, 29}, {103, 103, 53}, {104, 122, 29}, },
            {{36, 109, -21}, {110, 110, 54}, {111, 122, 29}, },
            {{36, 110, -19}, {111, 111, 55}, {112, 122, 29}, },
            {{36, 113, -24}, {114, 114, 56}, {115, 122, 29}, },
            {{36, 95, -12}, {97, 115, 29}, {116, 116, 57}, {117, 122, 29}, },
            {{36, 95, -12}, {97, 120, 29}, {121, 121, 58}, {122, 122, 29}, },
            {{36, 115, -42}, {116, 116, 59}, {117, 122, 29}, },
            {{36, 107, -20}, {108, 108, 60}, {109, 122, 29}, },
            {{36, 104, -18}, {105, 105, 61}, {106, 122, 29}, },
            {{36, 95, -12}, {97, 101, 29}, {102, 102, 62}, {103, 122, 29}, },
            {{36, 95, -12}, {97, 108, 29}, {109, 109, 63}, {110, 122, 29}, },
            {{36, 104, -18}, {105, 105, 64}, {106, 122, 29}, },
            {{36, 113, -24}, {114, 114, 65}, {115, 122, 29}, },
            {{36, 57, -12}, {65, 65, 66}, {66, 122, -17}, },
            {{36, 57, -12}, {65, 82, 29}, {83, 83, 67}, {84, 90, 29}, {95, 122, -12}, },
            {{36, 122, -12}, },
            {{36, 57, -12}, {65, 75, 29}, {76, 76, 68}, {77, 90, 29}, {95, 122, -12}, },
            {{36, 104, -18}, {105, 105, 69}, {106, 122, 29}, },
            {{36, 95, -12}, {97, 114, 29}, {115, 115, 70}, {116, 122, 29}, },
            {{36, 95, -12}, {97, 97, 71}, {98, 122, 29}, },
            {{36, 100, -22}, {101, 101, 72}, {102, 122, 29}, },
            {{36, 100, -22}, {101, 101, 73}, {102, 122, 29}, },
            {{36, 122, -12}, },
            {{36, 122, -12}, },
            {{36, 107, -20}, {108, 108, 74}, {109, 122, 29}, },
            {{36, 108, -48}, {109, 109, 75}, {110, 122, 29}, },
            {{36, 100, -22}, {101, 101, 76}, {102, 122, 29}, },
            {{36, 100, -22}, {101, 101, 77}, {102, 122, 29}, },
            {{36, 95, -12}, {97, 112, 29}, {113, 113, 78}, {114, 122, 29}, },
            {{36, 95, -12}, {97, 98, 29}, {99, 99, 79}, {100, 122, 29}, },
            {{36, 83, -36}, {84, 84, 80}, {85, 122, -36}, },
            {{36, 83, -36}, {84, 84, 81}, {85, 122, -36}, },
            {{36, 68, -33}, {69, 69, 82}, {70, 122, -33}, },
            {{36, 109, -21}, {110, 110, 83}, {111, 122, 29}, },
            {{36, 115, -42}, {116, 116, 84}, {117, 122, 29}, },
            {{36, 115, -42}, {116, 116, 85}, {117, 122, 29}, },
            {{36, 104, -18}, {105, 105, 86}, {106, 122, 29}, },
            {{36, 102, -38}, {103, 103, 87}, {104, 122, 29}, },
            {{36, 122, -12}, },
            {{36, 95, -12}, {97, 97, 88}, {98, 122, 29}, },
            {{36, 113, -24}, {114, 114, 89}, {115, 122, 29}, },
            {{36, 114, -56}, {115, 115, 90}, {116, 122, 29}, },
            {{36, 95, -12}, {97, 116, 29}, {117, 117, 91}, {118, 122, 29}, },
            {{36, 95, -12}, {97, 103, 29}, {104, 104, 92}, {105, 122, 29}, },
            {{36, 68, -33}, {69, 69, 93}, {70, 122, -33}, },
            {{36, 82, -52}, {83, 83, 94}, {84, 122, -52}, },
            {{36, 122, -12}, },
            {{36, 115, -42}, {116, 116, 95}, {117, 122, 29}, },
            {{36, 113, -24}, {114, 114, 96}, {115, 122, 29}, },
            {{36, 122, -12}, },
            {{36, 102, -38}, {103, 103, 97}, {104, 122, 29}, },
            {{36, 100, -22}, {101, 101, 98}, {102, 122, 29}, },
            {{36, 113, -24}, {114, 114, 99}, {115, 122, 29}, },
            {{36, 100, -22}, {101, 101, 100}, {102, 122, 29}, },
            {{36, 115, -42}, {116, 116, 101}, {117, 122, 29}, },
            {{36, 100, -22}, {101, 101, 102}, {102, 122, 29}, },
            {{36, 95, -12}, {97, 97, 103}, {98, 122, 29}, },
            {{36, 122, -12}, },
            {{36, 122, -12}, },
            {{36, 122, -12}, },
            {{36, 95, -12}, {97, 97, 104}, {98, 122, 29}, },
            {{36, 109, -21}, {110, 110, 105}, {111, 122, 29}, },
            {{36, 113, -24}, {114, 114, 106}, {115, 122, 29}, },
            {{36, 120, -43}, {121, 121, 107}, {122, 122, 29}, },
            {{36, 109, -21}, {110, 110, 108}, {111, 122, 29}, },
            {{36, 95, -12}, {97, 97, 109}, {98, 122, 29}, },
            {{36, 122, -12}, },
            {{36, 113, -24}, {114, 114, 110}, {115, 122, 29}, },
            {{36, 104, -18}, {105, 105, 111}, {106, 122, 29}, },
            {{36, 122, -12}, },
            {{36, 122, -12}, },
            {{36, 122, -12}, },
            {{36, 98, -67}, {99, 99, 112}, {100, 122, 29}, },
            {{36, 108, -48}, {109, 109, 113}, {110, 122, 29}, },
            {{36, 122, -12}, },
            {{36, 109, -21}, {110, 110, 114}, {111, 122, 29}, },
            {{36, 100, -22}, {101, 101, 115}, {102, 122, 29}, },
            {{36, 95, -12}, {97, 111, 29}, {112, 112, 116}, {113, 122, 29}, },
            {{36, 115, -42}, {116, 116, 117}, {117, 122, 29}, },
            {{36, 114, -56}, {115, 115, 118}, {116, 122, 29}, },
            {{36, 122, -12}, },
            {{36, 122, -12}, },
            {{36, 122, -12}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 22, 22, 22, 22, 1, 2, 3, 0, 4, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 7, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 19, 23, 23, 23, 23, 23, 23, 17, 19, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 20, 23, 23, 23, 23, 23, 23, 23, 6, 23, 23, 11, 23, 23, 23, 23, 23, 23, 23, 5, 8, 10, 23, 23, 23, 23, 23, 23, 18, 23, 23, 15, 9, 16, 23, 23, 13, 23, 23, 23, 23, 23, 12, 14, 21, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
