/* This file was generated by SableCC (http://www.sablecc.org/). */

package ddlgrammar.analysis;

import java.util.*;
import ddlgrammar.node.*;

public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPDdl().apply(this);
        outStart(node);
    }

    public void inADdl(ADdl node)
    {
        defaultIn(node);
    }

    public void outADdl(ADdl node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADdl(ADdl node)
    {
        inADdl(node);
        {
            List<PCreateTable> copy = new ArrayList<PCreateTable>(node.getCreateTable());
            Collections.reverse(copy);
            for(PCreateTable e : copy)
            {
                e.apply(this);
            }
        }
        outADdl(node);
    }

    public void inACreateTable(ACreateTable node)
    {
        defaultIn(node);
    }

    public void outACreateTable(ACreateTable node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACreateTable(ACreateTable node)
    {
        inACreateTable(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getTableDefinition() != null)
        {
            node.getTableDefinition().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        if(node.getExists() != null)
        {
            node.getExists().apply(this);
        }
        if(node.getNot() != null)
        {
            node.getNot().apply(this);
        }
        if(node.getIf() != null)
        {
            node.getIf().apply(this);
        }
        if(node.getTable() != null)
        {
            node.getTable().apply(this);
        }
        if(node.getCreate() != null)
        {
            node.getCreate().apply(this);
        }
        outACreateTable(node);
    }

    public void inATableDefinition(ATableDefinition node)
    {
        defaultIn(node);
    }

    public void outATableDefinition(ATableDefinition node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATableDefinition(ATableDefinition node)
    {
        inATableDefinition(node);
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        {
            List<PTableConstraintTail> copy = new ArrayList<PTableConstraintTail>(node.getTableConstraintTail());
            Collections.reverse(copy);
            for(PTableConstraintTail e : copy)
            {
                e.apply(this);
            }
        }
        {
            List<PAdditionColDef> copy = new ArrayList<PAdditionColDef>(node.getAdditionColDef());
            Collections.reverse(copy);
            for(PAdditionColDef e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getColDef() != null)
        {
            node.getColDef().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        outATableDefinition(node);
    }

    public void inAColDef(AColDef node)
    {
        defaultIn(node);
    }

    public void outAColDef(AColDef node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAColDef(AColDef node)
    {
        inAColDef(node);
        {
            List<PColConstraint> copy = new ArrayList<PColConstraint>(node.getColConstraint());
            Collections.reverse(copy);
            for(PColConstraint e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        outAColDef(node);
    }

    public void inAIntType(AIntType node)
    {
        defaultIn(node);
    }

    public void outAIntType(AIntType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIntType(AIntType node)
    {
        inAIntType(node);
        if(node.getInteger() != null)
        {
            node.getInteger().apply(this);
        }
        outAIntType(node);
    }

    public void inABigintType(ABigintType node)
    {
        defaultIn(node);
    }

    public void outABigintType(ABigintType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABigintType(ABigintType node)
    {
        inABigintType(node);
        if(node.getBigint() != null)
        {
            node.getBigint().apply(this);
        }
        outABigintType(node);
    }

    public void inAFloatType(AFloatType node)
    {
        defaultIn(node);
    }

    public void outAFloatType(AFloatType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFloatType(AFloatType node)
    {
        inAFloatType(node);
        if(node.getFloat() != null)
        {
            node.getFloat().apply(this);
        }
        outAFloatType(node);
    }

    public void inATimestampType(ATimestampType node)
    {
        defaultIn(node);
    }

    public void outATimestampType(ATimestampType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATimestampType(ATimestampType node)
    {
        inATimestampType(node);
        if(node.getTimestamp() != null)
        {
            node.getTimestamp().apply(this);
        }
        outATimestampType(node);
    }

    public void inACharsType(ACharsType node)
    {
        defaultIn(node);
    }

    public void outACharsType(ACharsType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACharsType(ACharsType node)
    {
        inACharsType(node);
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        {
            List<TNumber> copy = new ArrayList<TNumber>(node.getNumber());
            Collections.reverse(copy);
            for(TNumber e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getVarchar() != null)
        {
            node.getVarchar().apply(this);
        }
        outACharsType(node);
    }

    public void inAUniqueColConstraint(AUniqueColConstraint node)
    {
        defaultIn(node);
    }

    public void outAUniqueColConstraint(AUniqueColConstraint node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUniqueColConstraint(AUniqueColConstraint node)
    {
        inAUniqueColConstraint(node);
        if(node.getUnique() != null)
        {
            node.getUnique().apply(this);
        }
        outAUniqueColConstraint(node);
    }

    public void inANotNullColConstraint(ANotNullColConstraint node)
    {
        defaultIn(node);
    }

    public void outANotNullColConstraint(ANotNullColConstraint node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANotNullColConstraint(ANotNullColConstraint node)
    {
        inANotNullColConstraint(node);
        if(node.getNotNull() != null)
        {
            node.getNotNull().apply(this);
        }
        outANotNullColConstraint(node);
    }

    public void inANotNull(ANotNull node)
    {
        defaultIn(node);
    }

    public void outANotNull(ANotNull node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANotNull(ANotNull node)
    {
        inANotNull(node);
        if(node.getNull() != null)
        {
            node.getNull().apply(this);
        }
        if(node.getNot() != null)
        {
            node.getNot().apply(this);
        }
        outANotNull(node);
    }

    public void inAAdditionColDef(AAdditionColDef node)
    {
        defaultIn(node);
    }

    public void outAAdditionColDef(AAdditionColDef node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAdditionColDef(AAdditionColDef node)
    {
        inAAdditionColDef(node);
        if(node.getColDef() != null)
        {
            node.getColDef().apply(this);
        }
        if(node.getComma() != null)
        {
            node.getComma().apply(this);
        }
        outAAdditionColDef(node);
    }

    public void inATableConstraintList(ATableConstraintList node)
    {
        defaultIn(node);
    }

    public void outATableConstraintList(ATableConstraintList node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATableConstraintList(ATableConstraintList node)
    {
        inATableConstraintList(node);
        {
            List<PTableConstraintTail> copy = new ArrayList<PTableConstraintTail>(node.getTableConstraintTail());
            Collections.reverse(copy);
            for(PTableConstraintTail e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getTableConstraint() != null)
        {
            node.getTableConstraint().apply(this);
        }
        outATableConstraintList(node);
    }

    public void inAPrimaryKeyTableConstraint(APrimaryKeyTableConstraint node)
    {
        defaultIn(node);
    }

    public void outAPrimaryKeyTableConstraint(APrimaryKeyTableConstraint node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrimaryKeyTableConstraint(APrimaryKeyTableConstraint node)
    {
        inAPrimaryKeyTableConstraint(node);
        if(node.getPrimaryKey() != null)
        {
            node.getPrimaryKey().apply(this);
        }
        outAPrimaryKeyTableConstraint(node);
    }

    public void inAForeignKeyTableConstraint(AForeignKeyTableConstraint node)
    {
        defaultIn(node);
    }

    public void outAForeignKeyTableConstraint(AForeignKeyTableConstraint node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAForeignKeyTableConstraint(AForeignKeyTableConstraint node)
    {
        inAForeignKeyTableConstraint(node);
        if(node.getForeignKey() != null)
        {
            node.getForeignKey().apply(this);
        }
        outAForeignKeyTableConstraint(node);
    }

    public void inATableConstraintTail(ATableConstraintTail node)
    {
        defaultIn(node);
    }

    public void outATableConstraintTail(ATableConstraintTail node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATableConstraintTail(ATableConstraintTail node)
    {
        inATableConstraintTail(node);
        if(node.getTableConstraint() != null)
        {
            node.getTableConstraint().apply(this);
        }
        if(node.getComma() != null)
        {
            node.getComma().apply(this);
        }
        outATableConstraintTail(node);
    }

    public void inAPrimaryKey(APrimaryKey node)
    {
        defaultIn(node);
    }

    public void outAPrimaryKey(APrimaryKey node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrimaryKey(APrimaryKey node)
    {
        inAPrimaryKey(node);
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getCol() != null)
        {
            node.getCol().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getKey() != null)
        {
            node.getKey().apply(this);
        }
        if(node.getPrimary() != null)
        {
            node.getPrimary().apply(this);
        }
        if(node.getName() != null)
        {
            node.getName().apply(this);
        }
        if(node.getConstraint() != null)
        {
            node.getConstraint().apply(this);
        }
        outAPrimaryKey(node);
    }

    public void inAForeignKey(AForeignKey node)
    {
        defaultIn(node);
    }

    public void outAForeignKey(AForeignKey node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAForeignKey(AForeignKey node)
    {
        inAForeignKey(node);
        if(node.getReferencesClausel() != null)
        {
            node.getReferencesClausel().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getCols() != null)
        {
            node.getCols().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getKey() != null)
        {
            node.getKey().apply(this);
        }
        if(node.getForeign() != null)
        {
            node.getForeign().apply(this);
        }
        if(node.getName() != null)
        {
            node.getName().apply(this);
        }
        if(node.getConstraint() != null)
        {
            node.getConstraint().apply(this);
        }
        outAForeignKey(node);
    }

    public void inACols(ACols node)
    {
        defaultIn(node);
    }

    public void outACols(ACols node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACols(ACols node)
    {
        inACols(node);
        {
            List<PMoreIdentifier> copy = new ArrayList<PMoreIdentifier>(node.getMoreIdentifier());
            Collections.reverse(copy);
            for(PMoreIdentifier e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        outACols(node);
    }

    public void inAMoreIdentifier(AMoreIdentifier node)
    {
        defaultIn(node);
    }

    public void outAMoreIdentifier(AMoreIdentifier node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMoreIdentifier(AMoreIdentifier node)
    {
        inAMoreIdentifier(node);
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        if(node.getComma() != null)
        {
            node.getComma().apply(this);
        }
        outAMoreIdentifier(node);
    }

    public void inAReferencesClausel(AReferencesClausel node)
    {
        defaultIn(node);
    }

    public void outAReferencesClausel(AReferencesClausel node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAReferencesClausel(AReferencesClausel node)
    {
        inAReferencesClausel(node);
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getCols() != null)
        {
            node.getCols().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        if(node.getReferences() != null)
        {
            node.getReferences().apply(this);
        }
        outAReferencesClausel(node);
    }
}
