/* This file was generated by SableCC (http://www.sablecc.org/). */

package mysqlgrm.node;

import java.util.*;
import mysqlgrm.analysis.*;

@SuppressWarnings("nls")
public final class ACols extends PCols
{
    private TIdentifier _identifier_;
    private final LinkedList<PMoreIdentifier> _moreIdentifier_ = new LinkedList<PMoreIdentifier>();

    public ACols()
    {
        // Constructor
    }

    public ACols(
        @SuppressWarnings("hiding") TIdentifier _identifier_,
        @SuppressWarnings("hiding") List<?> _moreIdentifier_)
    {
        // Constructor
        setIdentifier(_identifier_);

        setMoreIdentifier(_moreIdentifier_);

    }

    @Override
    public Object clone()
    {
        return new ACols(
            cloneNode(this._identifier_),
            cloneList(this._moreIdentifier_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACols(this);
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public LinkedList<PMoreIdentifier> getMoreIdentifier()
    {
        return this._moreIdentifier_;
    }

    public void setMoreIdentifier(List<?> list)
    {
        for(PMoreIdentifier e : this._moreIdentifier_)
        {
            e.parent(null);
        }
        this._moreIdentifier_.clear();

        for(Object obj_e : list)
        {
            PMoreIdentifier e = (PMoreIdentifier) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._moreIdentifier_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identifier_)
            + toString(this._moreIdentifier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._moreIdentifier_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        for(ListIterator<PMoreIdentifier> i = this._moreIdentifier_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PMoreIdentifier) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
