/* This file was generated by SableCC (http://www.sablecc.org/). */

package mysqlgrm.node;

import java.util.*;
import mysqlgrm.analysis.*;

@SuppressWarnings("nls")
public final class AColDef extends PColDef
{
    private TIdentifier _identifier_;
    private PType _type_;
    private final LinkedList<PColConstraint> _colConstraint_ = new LinkedList<PColConstraint>();

    public AColDef()
    {
        // Constructor
    }

    public AColDef(
        @SuppressWarnings("hiding") TIdentifier _identifier_,
        @SuppressWarnings("hiding") PType _type_,
        @SuppressWarnings("hiding") List<?> _colConstraint_)
    {
        // Constructor
        setIdentifier(_identifier_);

        setType(_type_);

        setColConstraint(_colConstraint_);

    }

    @Override
    public Object clone()
    {
        return new AColDef(
            cloneNode(this._identifier_),
            cloneNode(this._type_),
            cloneList(this._colConstraint_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAColDef(this);
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public PType getType()
    {
        return this._type_;
    }

    public void setType(PType node)
    {
        if(this._type_ != null)
        {
            this._type_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._type_ = node;
    }

    public LinkedList<PColConstraint> getColConstraint()
    {
        return this._colConstraint_;
    }

    public void setColConstraint(List<?> list)
    {
        for(PColConstraint e : this._colConstraint_)
        {
            e.parent(null);
        }
        this._colConstraint_.clear();

        for(Object obj_e : list)
        {
            PColConstraint e = (PColConstraint) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._colConstraint_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identifier_)
            + toString(this._type_)
            + toString(this._colConstraint_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._type_ == child)
        {
            this._type_ = null;
            return;
        }

        if(this._colConstraint_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        if(this._type_ == oldChild)
        {
            setType((PType) newChild);
            return;
        }

        for(ListIterator<PColConstraint> i = this._colConstraint_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PColConstraint) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
