/* This file was generated by SableCC (http://www.sablecc.org/). */

package mysqlgrm.node;

import mysqlgrm.analysis.*;

@SuppressWarnings("nls")
public final class ADdlSttm extends PSttm
{
    private PDdl _ddl_;

    public ADdlSttm()
    {
        // Constructor
    }

    public ADdlSttm(
        @SuppressWarnings("hiding") PDdl _ddl_)
    {
        // Constructor
        setDdl(_ddl_);

    }

    @Override
    public Object clone()
    {
        return new ADdlSttm(
            cloneNode(this._ddl_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADdlSttm(this);
    }

    public PDdl getDdl()
    {
        return this._ddl_;
    }

    public void setDdl(PDdl node)
    {
        if(this._ddl_ != null)
        {
            this._ddl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ddl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ddl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ddl_ == child)
        {
            this._ddl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ddl_ == oldChild)
        {
            setDdl((PDdl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
