/* This file was generated by SableCC (http://www.sablecc.org/). */

package mysqlgrm.node;

import mysqlgrm.analysis.*;

@SuppressWarnings("nls")
public final class ADropDdl extends PDdl
{
    private PDropClausel _dropClausel_;
    private TSemicolon _semicolon_;

    public ADropDdl()
    {
        // Constructor
    }

    public ADropDdl(
        @SuppressWarnings("hiding") PDropClausel _dropClausel_,
        @SuppressWarnings("hiding") TSemicolon _semicolon_)
    {
        // Constructor
        setDropClausel(_dropClausel_);

        setSemicolon(_semicolon_);

    }

    @Override
    public Object clone()
    {
        return new ADropDdl(
            cloneNode(this._dropClausel_),
            cloneNode(this._semicolon_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADropDdl(this);
    }

    public PDropClausel getDropClausel()
    {
        return this._dropClausel_;
    }

    public void setDropClausel(PDropClausel node)
    {
        if(this._dropClausel_ != null)
        {
            this._dropClausel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dropClausel_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dropClausel_)
            + toString(this._semicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dropClausel_ == child)
        {
            this._dropClausel_ = null;
            return;
        }

        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dropClausel_ == oldChild)
        {
            setDropClausel((PDropClausel) newChild);
            return;
        }

        if(this._semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
