/* This file was generated by SableCC (http://www.sablecc.org/). */

package mysqlgrm.node;

import mysqlgrm.analysis.*;

@SuppressWarnings("nls")
public final class AFloatSingleValue extends PSingleValue
{
    private TFloatingPointNumber _floatingPointNumber_;

    public AFloatSingleValue()
    {
        // Constructor
    }

    public AFloatSingleValue(
        @SuppressWarnings("hiding") TFloatingPointNumber _floatingPointNumber_)
    {
        // Constructor
        setFloatingPointNumber(_floatingPointNumber_);

    }

    @Override
    public Object clone()
    {
        return new AFloatSingleValue(
            cloneNode(this._floatingPointNumber_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFloatSingleValue(this);
    }

    public TFloatingPointNumber getFloatingPointNumber()
    {
        return this._floatingPointNumber_;
    }

    public void setFloatingPointNumber(TFloatingPointNumber node)
    {
        if(this._floatingPointNumber_ != null)
        {
            this._floatingPointNumber_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._floatingPointNumber_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._floatingPointNumber_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._floatingPointNumber_ == child)
        {
            this._floatingPointNumber_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._floatingPointNumber_ == oldChild)
        {
            setFloatingPointNumber((TFloatingPointNumber) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
