/* This file was generated by SableCC (http://www.sablecc.org/). */

package mysqlgrm.node;

import mysqlgrm.analysis.*;

@SuppressWarnings("nls")
public final class AMoreValueClausel extends PMoreValueClausel
{
    private TComma _comma_;
    private PValueClausel _valueClausel_;

    public AMoreValueClausel()
    {
        // Constructor
    }

    public AMoreValueClausel(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PValueClausel _valueClausel_)
    {
        // Constructor
        setComma(_comma_);

        setValueClausel(_valueClausel_);

    }

    @Override
    public Object clone()
    {
        return new AMoreValueClausel(
            cloneNode(this._comma_),
            cloneNode(this._valueClausel_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMoreValueClausel(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PValueClausel getValueClausel()
    {
        return this._valueClausel_;
    }

    public void setValueClausel(PValueClausel node)
    {
        if(this._valueClausel_ != null)
        {
            this._valueClausel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valueClausel_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._valueClausel_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._valueClausel_ == child)
        {
            this._valueClausel_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._valueClausel_ == oldChild)
        {
            setValueClausel((PValueClausel) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
