/* This file was generated by SableCC (http://www.sablecc.org/). */

package mysqlgrm.node;

import mysqlgrm.analysis.*;

@SuppressWarnings("nls")
public final class AMoreSingleValue extends PMoreSingleValue
{
    private TComma _comma_;
    private PSingleValue _singleValue_;

    public AMoreSingleValue()
    {
        // Constructor
    }

    public AMoreSingleValue(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PSingleValue _singleValue_)
    {
        // Constructor
        setComma(_comma_);

        setSingleValue(_singleValue_);

    }

    @Override
    public Object clone()
    {
        return new AMoreSingleValue(
            cloneNode(this._comma_),
            cloneNode(this._singleValue_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMoreSingleValue(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PSingleValue getSingleValue()
    {
        return this._singleValue_;
    }

    public void setSingleValue(PSingleValue node)
    {
        if(this._singleValue_ != null)
        {
            this._singleValue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._singleValue_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._singleValue_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._singleValue_ == child)
        {
            this._singleValue_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._singleValue_ == oldChild)
        {
            setSingleValue((PSingleValue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
