/* This file was generated by SableCC (http://www.sablecc.org/). */

package mysqlgrm.node;

import mysqlgrm.analysis.*;

@SuppressWarnings("nls")
public final class ATruncateDdl extends PDdl
{
    private PTruncateClausel _truncateClausel_;
    private TSemicolon _semicolon_;

    public ATruncateDdl()
    {
        // Constructor
    }

    public ATruncateDdl(
        @SuppressWarnings("hiding") PTruncateClausel _truncateClausel_,
        @SuppressWarnings("hiding") TSemicolon _semicolon_)
    {
        // Constructor
        setTruncateClausel(_truncateClausel_);

        setSemicolon(_semicolon_);

    }

    @Override
    public Object clone()
    {
        return new ATruncateDdl(
            cloneNode(this._truncateClausel_),
            cloneNode(this._semicolon_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATruncateDdl(this);
    }

    public PTruncateClausel getTruncateClausel()
    {
        return this._truncateClausel_;
    }

    public void setTruncateClausel(PTruncateClausel node)
    {
        if(this._truncateClausel_ != null)
        {
            this._truncateClausel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._truncateClausel_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._truncateClausel_)
            + toString(this._semicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._truncateClausel_ == child)
        {
            this._truncateClausel_ = null;
            return;
        }

        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._truncateClausel_ == oldChild)
        {
            setTruncateClausel((PTruncateClausel) newChild);
            return;
        }

        if(this._semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
