/* This file was generated by SableCC (http://www.sablecc.org/). */

package mysqlgrm.node;

import java.util.*;
import mysqlgrm.analysis.*;

@SuppressWarnings("nls")
public final class AValueClauselList extends PValueClauselList
{
    private PValueClausel _valueClausel_;
    private final LinkedList<PMoreValueClausel> _moreValueClausel_ = new LinkedList<PMoreValueClausel>();

    public AValueClauselList()
    {
        // Constructor
    }

    public AValueClauselList(
        @SuppressWarnings("hiding") PValueClausel _valueClausel_,
        @SuppressWarnings("hiding") List<?> _moreValueClausel_)
    {
        // Constructor
        setValueClausel(_valueClausel_);

        setMoreValueClausel(_moreValueClausel_);

    }

    @Override
    public Object clone()
    {
        return new AValueClauselList(
            cloneNode(this._valueClausel_),
            cloneList(this._moreValueClausel_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAValueClauselList(this);
    }

    public PValueClausel getValueClausel()
    {
        return this._valueClausel_;
    }

    public void setValueClausel(PValueClausel node)
    {
        if(this._valueClausel_ != null)
        {
            this._valueClausel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valueClausel_ = node;
    }

    public LinkedList<PMoreValueClausel> getMoreValueClausel()
    {
        return this._moreValueClausel_;
    }

    public void setMoreValueClausel(List<?> list)
    {
        for(PMoreValueClausel e : this._moreValueClausel_)
        {
            e.parent(null);
        }
        this._moreValueClausel_.clear();

        for(Object obj_e : list)
        {
            PMoreValueClausel e = (PMoreValueClausel) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._moreValueClausel_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._valueClausel_)
            + toString(this._moreValueClausel_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._valueClausel_ == child)
        {
            this._valueClausel_ = null;
            return;
        }

        if(this._moreValueClausel_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._valueClausel_ == oldChild)
        {
            setValueClausel((PValueClausel) newChild);
            return;
        }

        for(ListIterator<PMoreValueClausel> i = this._moreValueClausel_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PMoreValueClausel) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
