/* This file was generated by SableCC (http://www.sablecc.org/). */

package mysqlgrm.analysis;

import mysqlgrm.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseASql(ASql node);
    void caseADdlSttm(ADdlSttm node);
    void caseADmlSttm(ADmlSttm node);
    void caseACreateDdl(ACreateDdl node);
    void caseATruncateDdl(ATruncateDdl node);
    void caseADropDdl(ADropDdl node);
    void caseACreateClausel(ACreateClausel node);
    void caseATableDefinition(ATableDefinition node);
    void caseAColDef(AColDef node);
    void caseAIntType(AIntType node);
    void caseABigintType(ABigintType node);
    void caseAFloatType(AFloatType node);
    void caseATimestampType(ATimestampType node);
    void caseACharsType(ACharsType node);
    void caseAUniqueColConstraint(AUniqueColConstraint node);
    void caseANotNullColConstraint(ANotNullColConstraint node);
    void caseANotNull(ANotNull node);
    void caseAAdditionColDef(AAdditionColDef node);
    void caseATableConstraintList(ATableConstraintList node);
    void caseAPrimaryKeyTableConstraint(APrimaryKeyTableConstraint node);
    void caseAForeignKeyTableConstraint(AForeignKeyTableConstraint node);
    void caseATableConstraintTail(ATableConstraintTail node);
    void caseAPrimaryKey(APrimaryKey node);
    void caseAForeignKey(AForeignKey node);
    void caseAIdentifierList(AIdentifierList node);
    void caseAMoreIdentifier(AMoreIdentifier node);
    void caseAReferencesClausel(AReferencesClausel node);
    void caseADropClausel(ADropClausel node);
    void caseATruncateClausel(ATruncateClausel node);
    void caseADml(ADml node);
    void caseAInsertClausel(AInsertClausel node);
    void caseAValueClauselList(AValueClauselList node);
    void caseAValueClausel(AValueClausel node);
    void caseAMoreValueClausel(AMoreValueClausel node);
    void caseAValues(AValues node);
    void caseAVarSingleValue(AVarSingleValue node);
    void caseAIntSingleValue(AIntSingleValue node);
    void caseAFloatSingleValue(AFloatSingleValue node);
    void caseAStringSingleValue(AStringSingleValue node);
    void caseAMoreSingleValue(AMoreSingleValue node);

    void caseTLPar(TLPar node);
    void caseTRPar(TRPar node);
    void caseTComma(TComma node);
    void caseTSemicolon(TSemicolon node);
    void caseTFloatingPointNumber(TFloatingPointNumber node);
    void caseTIntegerNumber(TIntegerNumber node);
    void caseTInteger(TInteger node);
    void caseTBigint(TBigint node);
    void caseTFloat(TFloat node);
    void caseTTimestamp(TTimestamp node);
    void caseTVarchar(TVarchar node);
    void caseTCreate(TCreate node);
    void caseTTable(TTable node);
    void caseTIf(TIf node);
    void caseTExists(TExists node);
    void caseTConstraint(TConstraint node);
    void caseTForeign(TForeign node);
    void caseTPrimary(TPrimary node);
    void caseTKey(TKey node);
    void caseTUnique(TUnique node);
    void caseTNot(TNot node);
    void caseTNull(TNull node);
    void caseTReferences(TReferences node);
    void caseTDrop(TDrop node);
    void caseTTruncate(TTruncate node);
    void caseTInsert(TInsert node);
    void caseTInto(TInto node);
    void caseTValues(TValues node);
    void caseTBlank(TBlank node);
    void caseTVar(TVar node);
    void caseTIdentifier(TIdentifier node);
    void caseTStringLiteral(TStringLiteral node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
