/* This file was generated by SableCC (http://www.sablecc.org/). */

package ddlgrammar.node;

import ddlgrammar.analysis.*;

@SuppressWarnings("nls")
public final class ABigintType extends PType
{
    private TBigint _bigint_;

    public ABigintType()
    {
        // Constructor
    }

    public ABigintType(
        @SuppressWarnings("hiding") TBigint _bigint_)
    {
        // Constructor
        setBigint(_bigint_);

    }

    @Override
    public Object clone()
    {
        return new ABigintType(
            cloneNode(this._bigint_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABigintType(this);
    }

    public TBigint getBigint()
    {
        return this._bigint_;
    }

    public void setBigint(TBigint node)
    {
        if(this._bigint_ != null)
        {
            this._bigint_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bigint_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._bigint_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._bigint_ == child)
        {
            this._bigint_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._bigint_ == oldChild)
        {
            setBigint((TBigint) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
