/* This file was generated by SableCC (http://www.sablecc.org/). */

package ddlgrammar.node;

import java.util.*;
import ddlgrammar.analysis.*;

@SuppressWarnings("nls")
public final class ADdl extends PDdl
{
    private final LinkedList<PCreateTable> _createTable_ = new LinkedList<PCreateTable>();

    public ADdl()
    {
        // Constructor
    }

    public ADdl(
        @SuppressWarnings("hiding") List<?> _createTable_)
    {
        // Constructor
        setCreateTable(_createTable_);

    }

    @Override
    public Object clone()
    {
        return new ADdl(
            cloneList(this._createTable_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADdl(this);
    }

    public LinkedList<PCreateTable> getCreateTable()
    {
        return this._createTable_;
    }

    public void setCreateTable(List<?> list)
    {
        for(PCreateTable e : this._createTable_)
        {
            e.parent(null);
        }
        this._createTable_.clear();

        for(Object obj_e : list)
        {
            PCreateTable e = (PCreateTable) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._createTable_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._createTable_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._createTable_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PCreateTable> i = this._createTable_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PCreateTable) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
