/* This file was generated by SableCC (http://www.sablecc.org/). */

package ddlgrammar.node;

import ddlgrammar.analysis.*;

@SuppressWarnings("nls")
public final class ANotNullColConstraint extends PColConstraint
{
    private PNotNull _notNull_;

    public ANotNullColConstraint()
    {
        // Constructor
    }

    public ANotNullColConstraint(
        @SuppressWarnings("hiding") PNotNull _notNull_)
    {
        // Constructor
        setNotNull(_notNull_);

    }

    @Override
    public Object clone()
    {
        return new ANotNullColConstraint(
            cloneNode(this._notNull_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotNullColConstraint(this);
    }

    public PNotNull getNotNull()
    {
        return this._notNull_;
    }

    public void setNotNull(PNotNull node)
    {
        if(this._notNull_ != null)
        {
            this._notNull_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._notNull_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._notNull_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._notNull_ == child)
        {
            this._notNull_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._notNull_ == oldChild)
        {
            setNotNull((PNotNull) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
