/* This file was generated by SableCC (http://www.sablecc.org/). */

package ddlgrammar.node;

import ddlgrammar.analysis.*;

@SuppressWarnings("nls")
public final class APrimaryKeyTableConstraint extends PTableConstraint
{
    private PPrimaryKey _primaryKey_;

    public APrimaryKeyTableConstraint()
    {
        // Constructor
    }

    public APrimaryKeyTableConstraint(
        @SuppressWarnings("hiding") PPrimaryKey _primaryKey_)
    {
        // Constructor
        setPrimaryKey(_primaryKey_);

    }

    @Override
    public Object clone()
    {
        return new APrimaryKeyTableConstraint(
            cloneNode(this._primaryKey_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrimaryKeyTableConstraint(this);
    }

    public PPrimaryKey getPrimaryKey()
    {
        return this._primaryKey_;
    }

    public void setPrimaryKey(PPrimaryKey node)
    {
        if(this._primaryKey_ != null)
        {
            this._primaryKey_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._primaryKey_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._primaryKey_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._primaryKey_ == child)
        {
            this._primaryKey_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._primaryKey_ == oldChild)
        {
            setPrimaryKey((PPrimaryKey) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
