/* This file was generated by SableCC (http://www.sablecc.org/). */

package ddlgrammar.node;

import ddlgrammar.analysis.*;

@SuppressWarnings("nls")
public final class AUniqueColConstraint extends PColConstraint
{
    private TUnique _unique_;

    public AUniqueColConstraint()
    {
        // Constructor
    }

    public AUniqueColConstraint(
        @SuppressWarnings("hiding") TUnique _unique_)
    {
        // Constructor
        setUnique(_unique_);

    }

    @Override
    public Object clone()
    {
        return new AUniqueColConstraint(
            cloneNode(this._unique_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUniqueColConstraint(this);
    }

    public TUnique getUnique()
    {
        return this._unique_;
    }

    public void setUnique(TUnique node)
    {
        if(this._unique_ != null)
        {
            this._unique_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unique_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._unique_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._unique_ == child)
        {
            this._unique_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._unique_ == oldChild)
        {
            setUnique((TUnique) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
