/* This file was generated by SableCC (http://www.sablecc.org/). */

package ddlgrammar.node;

import ddlgrammar.analysis.*;

@SuppressWarnings("nls")
public final class TConstraint extends Token
{
    public TConstraint()
    {
        super.setText("constraint");
    }

    public TConstraint(int line, int pos)
    {
        super.setText("constraint");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TConstraint(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTConstraint(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TConstraint text.");
    }
}
