/* This file was generated by SableCC (http://www.sablecc.org/). */

package ddlgrammar.node;

import ddlgrammar.analysis.*;

@SuppressWarnings("nls")
public final class TExists extends Token
{
    public TExists()
    {
        super.setText("EXISTS");
    }

    public TExists(int line, int pos)
    {
        super.setText("EXISTS");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TExists(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTExists(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TExists text.");
    }
}
