/* This file was generated by SableCC (http://www.sablecc.org/). */

package ddlgrammar.node;

import ddlgrammar.analysis.*;

@SuppressWarnings("nls")
public final class TReferences extends Token
{
    public TReferences()
    {
        super.setText("references");
    }

    public TReferences(int line, int pos)
    {
        super.setText("references");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TReferences(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTReferences(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TReferences text.");
    }
}
