/* This file was generated by SableCC (http://www.sablecc.org/). */

package ddlgrammar.node;

import ddlgrammar.analysis.*;

@SuppressWarnings("nls")
public final class TTable extends Token
{
    public TTable()
    {
        super.setText("TABLE");
    }

    public TTable(int line, int pos)
    {
        super.setText("TABLE");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTable(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTable(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTable text.");
    }
}
