/* This file was generated by SableCC (http://www.sablecc.org/). */

package ddlgrammar.node;

import ddlgrammar.analysis.*;

@SuppressWarnings("nls")
public final class TTimestamp extends Token
{
    public TTimestamp()
    {
        super.setText("timestamp");
    }

    public TTimestamp(int line, int pos)
    {
        super.setText("timestamp");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTimestamp(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTimestamp(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTimestamp text.");
    }
}
