/* This file was generated by SableCC (http://www.sablecc.org/). */

package mysqlgrm.parser;

import mysqlgrm.lexer.*;
import mysqlgrm.node.*;
import mysqlgrm.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

@SuppressWarnings("nls")
public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList<Object> nodeList;

    private final Lexer lexer;
    private final ListIterator<Object> stack = new LinkedList<Object>().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(@SuppressWarnings("hiding") Lexer lexer)
    {
        this.lexer = lexer;
    }

    protected void filter() throws ParserException, LexerException, IOException
    {
        // Empty body
    }

    private void push(int numstate, ArrayList<Object> listNode, boolean hidden) throws ParserException, LexerException, IOException
    {
        this.nodeList = listNode;

        if(!hidden)
        {
            filter();
        }

        if(!this.stack.hasNext())
        {
            this.stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) this.stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            // int middle = (low + high) / 2;
            int middle = (low + high) >>> 1;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) this.stack.previous();
        this.stack.next();
        return s.state;
    }

    private ArrayList<Object> pop()
    {
        return ((State) this.stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        this.converter.index = -1;
        token.apply(this.converter);
        return this.converter.index;
    }

    @SuppressWarnings("unchecked")
    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null, true);
        List<Node> ign = null;
        while(true)
        {
            while(index(this.lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new LinkedList<Node>();
                }

                ign.add(this.lexer.next());
            }

            if(ign != null)
            {
                this.ignoredTokens.setIn(this.lexer.peek(), ign);
                ign = null;
            }

            this.last_pos = this.lexer.peek().getPos();
            this.last_line = this.lexer.peek().getLine();
            this.last_token = this.lexer.peek();

            int index = index(this.lexer.peek());
            this.action[0] = Parser.actionTable[state()][0][1];
            this.action[1] = Parser.actionTable[state()][0][2];

            int low = 1;
            int high = Parser.actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < Parser.actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > Parser.actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    this.action[0] = Parser.actionTable[state()][middle][1];
                    this.action[1] = Parser.actionTable[state()][middle][2];
                    break;
                }
            }

            switch(this.action[0])
            {
                case SHIFT:
		    {
		        ArrayList<Object> list = new ArrayList<Object>();
		        list.add(this.lexer.next());
                        push(this.action[1], list, false);
                    }
		    break;
                case REDUCE:
                    {
                        int reduction = this.action[1];
                        if(reduction < 500) reduce_0(reduction);
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) this.lexer.next();
                        PSql node1 = (PSql) pop().get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(this.last_token,
                        "[" + this.last_line + "," + this.last_pos + "] " +
                        Parser.errorMessages[Parser.errors[this.action[1]]]);
            }
        }
    }

    private void reduce_0(int reduction) throws IOException, LexerException, ParserException
    {
        switch(reduction)
        {
            case 0: /* reduce ASql */
            {
                ArrayList<Object> list = new0();
                push(goTo(0), list, false);
            }
            break;
            case 1: /* reduce ADdlSttm */
            {
                ArrayList<Object> list = new1();
                push(goTo(1), list, false);
            }
            break;
            case 2: /* reduce ADmlSttm */
            {
                ArrayList<Object> list = new2();
                push(goTo(1), list, false);
            }
            break;
            case 3: /* reduce ACreateDdl */
            {
                ArrayList<Object> list = new3();
                push(goTo(2), list, false);
            }
            break;
            case 4: /* reduce ATruncateDdl */
            {
                ArrayList<Object> list = new4();
                push(goTo(2), list, false);
            }
            break;
            case 5: /* reduce ADropDdl */
            {
                ArrayList<Object> list = new5();
                push(goTo(2), list, false);
            }
            break;
            case 6: /* reduce ACreateClausel */
            {
                ArrayList<Object> list = new6();
                push(goTo(3), list, false);
            }
            break;
            case 7: /* reduce AAtabledefinition1TableDefinition */
            {
                ArrayList<Object> list = new7();
                push(goTo(4), list, false);
            }
            break;
            case 8: /* reduce AAtabledefinition2TableDefinition */
            {
                ArrayList<Object> list = new8();
                push(goTo(4), list, false);
            }
            break;
            case 9: /* reduce AAtabledefinition3TableDefinition */
            {
                ArrayList<Object> list = new9();
                push(goTo(4), list, false);
            }
            break;
            case 10: /* reduce AAtabledefinition4TableDefinition */
            {
                ArrayList<Object> list = new10();
                push(goTo(4), list, false);
            }
            break;
            case 11: /* reduce AAcoldef1ColDef */
            {
                ArrayList<Object> list = new11();
                push(goTo(5), list, false);
            }
            break;
            case 12: /* reduce AAcoldef2ColDef */
            {
                ArrayList<Object> list = new12();
                push(goTo(5), list, false);
            }
            break;
            case 13: /* reduce AIntType */
            {
                ArrayList<Object> list = new13();
                push(goTo(6), list, false);
            }
            break;
            case 14: /* reduce ABigintType */
            {
                ArrayList<Object> list = new14();
                push(goTo(6), list, false);
            }
            break;
            case 15: /* reduce AFloatType */
            {
                ArrayList<Object> list = new15();
                push(goTo(6), list, false);
            }
            break;
            case 16: /* reduce ATimestampType */
            {
                ArrayList<Object> list = new16();
                push(goTo(6), list, false);
            }
            break;
            case 17: /* reduce ACharsType */
            {
                ArrayList<Object> list = new17();
                push(goTo(6), list, false);
            }
            break;
            case 18: /* reduce AUniqueColConstraint */
            {
                ArrayList<Object> list = new18();
                push(goTo(7), list, false);
            }
            break;
            case 19: /* reduce ANotNullColConstraint */
            {
                ArrayList<Object> list = new19();
                push(goTo(7), list, false);
            }
            break;
            case 20: /* reduce ANotNull */
            {
                ArrayList<Object> list = new20();
                push(goTo(8), list, false);
            }
            break;
            case 21: /* reduce AAdditionColDef */
            {
                ArrayList<Object> list = new21();
                push(goTo(9), list, false);
            }
            break;
            case 22: /* reduce AAtableconstraintlist1TableConstraintList */
            {
                ArrayList<Object> list = new22();
                push(goTo(10), list, false);
            }
            break;
            case 23: /* reduce AAtableconstraintlist2TableConstraintList */
            {
                ArrayList<Object> list = new23();
                push(goTo(10), list, false);
            }
            break;
            case 24: /* reduce APrimaryKeyTableConstraint */
            {
                ArrayList<Object> list = new24();
                push(goTo(11), list, false);
            }
            break;
            case 25: /* reduce AForeignKeyTableConstraint */
            {
                ArrayList<Object> list = new25();
                push(goTo(11), list, false);
            }
            break;
            case 26: /* reduce ATableConstraintTail */
            {
                ArrayList<Object> list = new26();
                push(goTo(12), list, false);
            }
            break;
            case 27: /* reduce APrimaryKey */
            {
                ArrayList<Object> list = new27();
                push(goTo(13), list, false);
            }
            break;
            case 28: /* reduce AForeignKey */
            {
                ArrayList<Object> list = new28();
                push(goTo(14), list, false);
            }
            break;
            case 29: /* reduce AAidentifierlist1IdentifierList */
            {
                ArrayList<Object> list = new29();
                push(goTo(15), list, false);
            }
            break;
            case 30: /* reduce AAidentifierlist2IdentifierList */
            {
                ArrayList<Object> list = new30();
                push(goTo(15), list, false);
            }
            break;
            case 31: /* reduce AMoreIdentifier */
            {
                ArrayList<Object> list = new31();
                push(goTo(16), list, false);
            }
            break;
            case 32: /* reduce AReferencesClausel */
            {
                ArrayList<Object> list = new32();
                push(goTo(17), list, false);
            }
            break;
            case 33: /* reduce AAdropclausel1DropClausel */
            {
                ArrayList<Object> list = new33();
                push(goTo(18), list, false);
            }
            break;
            case 34: /* reduce AAdropclausel2DropClausel */
            {
                ArrayList<Object> list = new34();
                push(goTo(18), list, false);
            }
            break;
            case 35: /* reduce ATruncateClausel */
            {
                ArrayList<Object> list = new35();
                push(goTo(19), list, false);
            }
            break;
            case 36: /* reduce ADml */
            {
                ArrayList<Object> list = new36();
                push(goTo(20), list, false);
            }
            break;
            case 37: /* reduce AInsertClausel */
            {
                ArrayList<Object> list = new37();
                push(goTo(21), list, false);
            }
            break;
            case 38: /* reduce AAvalueclausellist1ValueClauselList */
            {
                ArrayList<Object> list = new38();
                push(goTo(22), list, false);
            }
            break;
            case 39: /* reduce AAvalueclausellist2ValueClauselList */
            {
                ArrayList<Object> list = new39();
                push(goTo(22), list, false);
            }
            break;
            case 40: /* reduce AValueClausel */
            {
                ArrayList<Object> list = new40();
                push(goTo(23), list, false);
            }
            break;
            case 41: /* reduce AMoreValueClausel */
            {
                ArrayList<Object> list = new41();
                push(goTo(24), list, false);
            }
            break;
            case 42: /* reduce AAvalues1Values */
            {
                ArrayList<Object> list = new42();
                push(goTo(25), list, false);
            }
            break;
            case 43: /* reduce AAvalues2Values */
            {
                ArrayList<Object> list = new43();
                push(goTo(25), list, false);
            }
            break;
            case 44: /* reduce AVarSingleValue */
            {
                ArrayList<Object> list = new44();
                push(goTo(26), list, false);
            }
            break;
            case 45: /* reduce AIntSingleValue */
            {
                ArrayList<Object> list = new45();
                push(goTo(26), list, false);
            }
            break;
            case 46: /* reduce AFloatSingleValue */
            {
                ArrayList<Object> list = new46();
                push(goTo(26), list, false);
            }
            break;
            case 47: /* reduce AStringSingleValue */
            {
                ArrayList<Object> list = new47();
                push(goTo(26), list, false);
            }
            break;
            case 48: /* reduce AMoreSingleValue */
            {
                ArrayList<Object> list = new48();
                push(goTo(27), list, false);
            }
            break;
            case 49: /* reduce ATerminal$Sttm */
            {
                ArrayList<Object> list = new49();
                push(goTo(28), list, true);
            }
            break;
            case 50: /* reduce ANonTerminal$Sttm */
            {
                ArrayList<Object> list = new50();
                push(goTo(28), list, true);
            }
            break;
            case 51: /* reduce ATerminal$AdditionColDef */
            {
                ArrayList<Object> list = new51();
                push(goTo(29), list, true);
            }
            break;
            case 52: /* reduce ANonTerminal$AdditionColDef */
            {
                ArrayList<Object> list = new52();
                push(goTo(29), list, true);
            }
            break;
            case 53: /* reduce ATerminal$TableConstraintTail */
            {
                ArrayList<Object> list = new53();
                push(goTo(30), list, true);
            }
            break;
            case 54: /* reduce ANonTerminal$TableConstraintTail */
            {
                ArrayList<Object> list = new54();
                push(goTo(30), list, true);
            }
            break;
            case 55: /* reduce ATerminal$ColConstraint */
            {
                ArrayList<Object> list = new55();
                push(goTo(31), list, true);
            }
            break;
            case 56: /* reduce ANonTerminal$ColConstraint */
            {
                ArrayList<Object> list = new56();
                push(goTo(31), list, true);
            }
            break;
            case 57: /* reduce ATerminal$IntegerNumber */
            {
                ArrayList<Object> list = new57();
                push(goTo(32), list, true);
            }
            break;
            case 58: /* reduce ANonTerminal$IntegerNumber */
            {
                ArrayList<Object> list = new58();
                push(goTo(32), list, true);
            }
            break;
            case 59: /* reduce ATerminal$MoreIdentifier */
            {
                ArrayList<Object> list = new59();
                push(goTo(33), list, true);
            }
            break;
            case 60: /* reduce ANonTerminal$MoreIdentifier */
            {
                ArrayList<Object> list = new60();
                push(goTo(33), list, true);
            }
            break;
            case 61: /* reduce ATerminal$MoreValueClausel */
            {
                ArrayList<Object> list = new61();
                push(goTo(34), list, true);
            }
            break;
            case 62: /* reduce ANonTerminal$MoreValueClausel */
            {
                ArrayList<Object> list = new62();
                push(goTo(34), list, true);
            }
            break;
            case 63: /* reduce ATerminal$MoreSingleValue */
            {
                ArrayList<Object> list = new63();
                push(goTo(35), list, true);
            }
            break;
            case 64: /* reduce ANonTerminal$MoreSingleValue */
            {
                ArrayList<Object> list = new64();
                push(goTo(35), list, true);
            }
            break;
        }
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new0() /* reduce ASql */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PSql psqlNode1;
        {
            // Block
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        listNode2 = (LinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        psqlNode1 = new ASql(listNode3);
        }
	nodeList.add(psqlNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new1() /* reduce ADdlSttm */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PSttm psttmNode1;
        {
            // Block
        PDdl pddlNode2;
        pddlNode2 = (PDdl)nodeArrayList1.get(0);

        psttmNode1 = new ADdlSttm(pddlNode2);
        }
	nodeList.add(psttmNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new2() /* reduce ADmlSttm */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PSttm psttmNode1;
        {
            // Block
        PDml pdmlNode2;
        pdmlNode2 = (PDml)nodeArrayList1.get(0);

        psttmNode1 = new ADmlSttm(pdmlNode2);
        }
	nodeList.add(psttmNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new3() /* reduce ACreateDdl */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDdl pddlNode1;
        {
            // Block
        PCreateClausel pcreateclauselNode2;
        TSemicolon tsemicolonNode3;
        pcreateclauselNode2 = (PCreateClausel)nodeArrayList1.get(0);
        tsemicolonNode3 = (TSemicolon)nodeArrayList2.get(0);

        pddlNode1 = new ACreateDdl(pcreateclauselNode2, tsemicolonNode3);
        }
	nodeList.add(pddlNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new4() /* reduce ATruncateDdl */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDdl pddlNode1;
        {
            // Block
        PTruncateClausel ptruncateclauselNode2;
        TSemicolon tsemicolonNode3;
        ptruncateclauselNode2 = (PTruncateClausel)nodeArrayList1.get(0);
        tsemicolonNode3 = (TSemicolon)nodeArrayList2.get(0);

        pddlNode1 = new ATruncateDdl(ptruncateclauselNode2, tsemicolonNode3);
        }
	nodeList.add(pddlNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new5() /* reduce ADropDdl */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDdl pddlNode1;
        {
            // Block
        PDropClausel pdropclauselNode2;
        TSemicolon tsemicolonNode3;
        pdropclauselNode2 = (PDropClausel)nodeArrayList1.get(0);
        tsemicolonNode3 = (TSemicolon)nodeArrayList2.get(0);

        pddlNode1 = new ADropDdl(pdropclauselNode2, tsemicolonNode3);
        }
	nodeList.add(pddlNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new6() /* reduce ACreateClausel */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PCreateClausel pcreateclauselNode1;
        {
            // Block
        TCreate tcreateNode2;
        TTable ttableNode3;
        TIf tifNode4;
        TNot tnotNode5;
        TExists texistsNode6;
        TIdentifier tidentifierNode7;
        PTableDefinition ptabledefinitionNode8;
        tcreateNode2 = (TCreate)nodeArrayList1.get(0);
        ttableNode3 = (TTable)nodeArrayList2.get(0);
        tifNode4 = (TIf)nodeArrayList3.get(0);
        tnotNode5 = (TNot)nodeArrayList4.get(0);
        texistsNode6 = (TExists)nodeArrayList5.get(0);
        tidentifierNode7 = (TIdentifier)nodeArrayList6.get(0);
        ptabledefinitionNode8 = (PTableDefinition)nodeArrayList7.get(0);

        pcreateclauselNode1 = new ACreateClausel(tcreateNode2, ttableNode3, tifNode4, tnotNode5, texistsNode6, tidentifierNode7, ptabledefinitionNode8);
        }
	nodeList.add(pcreateclauselNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new7() /* reduce AAtabledefinition1TableDefinition */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTableDefinition ptabledefinitionNode1;
        {
            // Block
        TLPar tlparNode2;
        PColDef pcoldefNode3;
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        LinkedList<Object> listNode5 = new LinkedList<Object>();
        TRPar trparNode6;
        tlparNode2 = (TLPar)nodeArrayList1.get(0);
        pcoldefNode3 = (PColDef)nodeArrayList2.get(0);
        {
            // Block
        }
        {
            // Block
        }
        trparNode6 = (TRPar)nodeArrayList3.get(0);

        ptabledefinitionNode1 = new ATableDefinition(tlparNode2, pcoldefNode3, listNode4, listNode5, trparNode6);
        }
	nodeList.add(ptabledefinitionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new8() /* reduce AAtabledefinition2TableDefinition */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTableDefinition ptabledefinitionNode1;
        {
            // Block
        TLPar tlparNode2;
        PColDef pcoldefNode3;
        LinkedList<Object> listNode5 = new LinkedList<Object>();
        LinkedList<Object> listNode6 = new LinkedList<Object>();
        TRPar trparNode7;
        tlparNode2 = (TLPar)nodeArrayList1.get(0);
        pcoldefNode3 = (PColDef)nodeArrayList2.get(0);
        {
            // Block
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        listNode4 = (LinkedList)nodeArrayList3.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }
        {
            // Block
        }
        trparNode7 = (TRPar)nodeArrayList4.get(0);

        ptabledefinitionNode1 = new ATableDefinition(tlparNode2, pcoldefNode3, listNode5, listNode6, trparNode7);
        }
	nodeList.add(ptabledefinitionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new9() /* reduce AAtabledefinition3TableDefinition */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTableDefinition ptabledefinitionNode1;
        {
            // Block
        TLPar tlparNode2;
        PColDef pcoldefNode3;
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        LinkedList<Object> listNode6 = new LinkedList<Object>();
        TRPar trparNode7;
        tlparNode2 = (TLPar)nodeArrayList1.get(0);
        pcoldefNode3 = (PColDef)nodeArrayList2.get(0);
        {
            // Block
        }
        {
            // Block
        LinkedList<Object> listNode5 = new LinkedList<Object>();
        listNode5 = (LinkedList)nodeArrayList3.get(0);
	if(listNode5 != null)
	{
	  listNode6.addAll(listNode5);
	}
        }
        trparNode7 = (TRPar)nodeArrayList4.get(0);

        ptabledefinitionNode1 = new ATableDefinition(tlparNode2, pcoldefNode3, listNode4, listNode6, trparNode7);
        }
	nodeList.add(ptabledefinitionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new10() /* reduce AAtabledefinition4TableDefinition */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTableDefinition ptabledefinitionNode1;
        {
            // Block
        TLPar tlparNode2;
        PColDef pcoldefNode3;
        LinkedList<Object> listNode5 = new LinkedList<Object>();
        LinkedList<Object> listNode7 = new LinkedList<Object>();
        TRPar trparNode8;
        tlparNode2 = (TLPar)nodeArrayList1.get(0);
        pcoldefNode3 = (PColDef)nodeArrayList2.get(0);
        {
            // Block
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        listNode4 = (LinkedList)nodeArrayList3.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }
        {
            // Block
        LinkedList<Object> listNode6 = new LinkedList<Object>();
        listNode6 = (LinkedList)nodeArrayList4.get(0);
	if(listNode6 != null)
	{
	  listNode7.addAll(listNode6);
	}
        }
        trparNode8 = (TRPar)nodeArrayList5.get(0);

        ptabledefinitionNode1 = new ATableDefinition(tlparNode2, pcoldefNode3, listNode5, listNode7, trparNode8);
        }
	nodeList.add(ptabledefinitionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new11() /* reduce AAcoldef1ColDef */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PColDef pcoldefNode1;
        {
            // Block
        TIdentifier tidentifierNode2;
        PType ptypeNode3;
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        tidentifierNode2 = (TIdentifier)nodeArrayList1.get(0);
        ptypeNode3 = (PType)nodeArrayList2.get(0);
        {
            // Block
        }

        pcoldefNode1 = new AColDef(tidentifierNode2, ptypeNode3, listNode4);
        }
	nodeList.add(pcoldefNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new12() /* reduce AAcoldef2ColDef */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PColDef pcoldefNode1;
        {
            // Block
        TIdentifier tidentifierNode2;
        PType ptypeNode3;
        LinkedList<Object> listNode5 = new LinkedList<Object>();
        tidentifierNode2 = (TIdentifier)nodeArrayList1.get(0);
        ptypeNode3 = (PType)nodeArrayList2.get(0);
        {
            // Block
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        listNode4 = (LinkedList)nodeArrayList3.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        pcoldefNode1 = new AColDef(tidentifierNode2, ptypeNode3, listNode5);
        }
	nodeList.add(pcoldefNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new13() /* reduce AIntType */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PType ptypeNode1;
        {
            // Block
        TInteger tintegerNode2;
        tintegerNode2 = (TInteger)nodeArrayList1.get(0);

        ptypeNode1 = new AIntType(tintegerNode2);
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new14() /* reduce ABigintType */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PType ptypeNode1;
        {
            // Block
        TBigint tbigintNode2;
        tbigintNode2 = (TBigint)nodeArrayList1.get(0);

        ptypeNode1 = new ABigintType(tbigintNode2);
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new15() /* reduce AFloatType */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PType ptypeNode1;
        {
            // Block
        TFloat tfloatNode2;
        tfloatNode2 = (TFloat)nodeArrayList1.get(0);

        ptypeNode1 = new AFloatType(tfloatNode2);
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new16() /* reduce ATimestampType */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PType ptypeNode1;
        {
            // Block
        TTimestamp ttimestampNode2;
        ttimestampNode2 = (TTimestamp)nodeArrayList1.get(0);

        ptypeNode1 = new ATimestampType(ttimestampNode2);
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new17() /* reduce ACharsType */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PType ptypeNode1;
        {
            // Block
        TVarchar tvarcharNode2;
        TLPar tlparNode3;
        LinkedList<Object> listNode5 = new LinkedList<Object>();
        TRPar trparNode6;
        tvarcharNode2 = (TVarchar)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        {
            // Block
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        listNode4 = (LinkedList)nodeArrayList3.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }
        trparNode6 = (TRPar)nodeArrayList4.get(0);

        ptypeNode1 = new ACharsType(tvarcharNode2, tlparNode3, listNode5, trparNode6);
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new18() /* reduce AUniqueColConstraint */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PColConstraint pcolconstraintNode1;
        {
            // Block
        TUnique tuniqueNode2;
        tuniqueNode2 = (TUnique)nodeArrayList1.get(0);

        pcolconstraintNode1 = new AUniqueColConstraint(tuniqueNode2);
        }
	nodeList.add(pcolconstraintNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new19() /* reduce ANotNullColConstraint */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PColConstraint pcolconstraintNode1;
        {
            // Block
        PNotNull pnotnullNode2;
        pnotnullNode2 = (PNotNull)nodeArrayList1.get(0);

        pcolconstraintNode1 = new ANotNullColConstraint(pnotnullNode2);
        }
	nodeList.add(pcolconstraintNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new20() /* reduce ANotNull */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PNotNull pnotnullNode1;
        {
            // Block
        TNot tnotNode2;
        TNull tnullNode3;
        tnotNode2 = (TNot)nodeArrayList1.get(0);
        tnullNode3 = (TNull)nodeArrayList2.get(0);

        pnotnullNode1 = new ANotNull(tnotNode2, tnullNode3);
        }
	nodeList.add(pnotnullNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new21() /* reduce AAdditionColDef */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PAdditionColDef padditioncoldefNode1;
        {
            // Block
        TComma tcommaNode2;
        PColDef pcoldefNode3;
        tcommaNode2 = (TComma)nodeArrayList1.get(0);
        pcoldefNode3 = (PColDef)nodeArrayList2.get(0);

        padditioncoldefNode1 = new AAdditionColDef(tcommaNode2, pcoldefNode3);
        }
	nodeList.add(padditioncoldefNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new22() /* reduce AAtableconstraintlist1TableConstraintList */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTableConstraintList ptableconstraintlistNode1;
        {
            // Block
        PTableConstraint ptableconstraintNode2;
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        ptableconstraintNode2 = (PTableConstraint)nodeArrayList1.get(0);
        {
            // Block
        }

        ptableconstraintlistNode1 = new ATableConstraintList(ptableconstraintNode2, listNode3);
        }
	nodeList.add(ptableconstraintlistNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new23() /* reduce AAtableconstraintlist2TableConstraintList */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTableConstraintList ptableconstraintlistNode1;
        {
            // Block
        PTableConstraint ptableconstraintNode2;
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        ptableconstraintNode2 = (PTableConstraint)nodeArrayList1.get(0);
        {
            // Block
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        listNode3 = (LinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        ptableconstraintlistNode1 = new ATableConstraintList(ptableconstraintNode2, listNode4);
        }
	nodeList.add(ptableconstraintlistNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new24() /* reduce APrimaryKeyTableConstraint */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTableConstraint ptableconstraintNode1;
        {
            // Block
        PPrimaryKey pprimarykeyNode2;
        pprimarykeyNode2 = (PPrimaryKey)nodeArrayList1.get(0);

        ptableconstraintNode1 = new APrimaryKeyTableConstraint(pprimarykeyNode2);
        }
	nodeList.add(ptableconstraintNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new25() /* reduce AForeignKeyTableConstraint */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTableConstraint ptableconstraintNode1;
        {
            // Block
        PForeignKey pforeignkeyNode2;
        pforeignkeyNode2 = (PForeignKey)nodeArrayList1.get(0);

        ptableconstraintNode1 = new AForeignKeyTableConstraint(pforeignkeyNode2);
        }
	nodeList.add(ptableconstraintNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new26() /* reduce ATableConstraintTail */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTableConstraintTail ptableconstrainttailNode1;
        {
            // Block
        TComma tcommaNode2;
        PTableConstraint ptableconstraintNode3;
        tcommaNode2 = (TComma)nodeArrayList1.get(0);
        ptableconstraintNode3 = (PTableConstraint)nodeArrayList2.get(0);

        ptableconstrainttailNode1 = new ATableConstraintTail(tcommaNode2, ptableconstraintNode3);
        }
	nodeList.add(ptableconstrainttailNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new27() /* reduce APrimaryKey */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PPrimaryKey pprimarykeyNode1;
        {
            // Block
        TConstraint tconstraintNode2;
        TIdentifier tidentifierNode3;
        TPrimary tprimaryNode4;
        TKey tkeyNode5;
        TLPar tlparNode6;
        TIdentifier tidentifierNode7;
        TRPar trparNode8;
        tconstraintNode2 = (TConstraint)nodeArrayList1.get(0);
        tidentifierNode3 = (TIdentifier)nodeArrayList2.get(0);
        tprimaryNode4 = (TPrimary)nodeArrayList3.get(0);
        tkeyNode5 = (TKey)nodeArrayList4.get(0);
        tlparNode6 = (TLPar)nodeArrayList5.get(0);
        tidentifierNode7 = (TIdentifier)nodeArrayList6.get(0);
        trparNode8 = (TRPar)nodeArrayList7.get(0);

        pprimarykeyNode1 = new APrimaryKey(tconstraintNode2, tidentifierNode3, tprimaryNode4, tkeyNode5, tlparNode6, tidentifierNode7, trparNode8);
        }
	nodeList.add(pprimarykeyNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new28() /* reduce AForeignKey */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PForeignKey pforeignkeyNode1;
        {
            // Block
        TConstraint tconstraintNode2;
        TIdentifier tidentifierNode3;
        TForeign tforeignNode4;
        TKey tkeyNode5;
        TLPar tlparNode6;
        PIdentifierList pidentifierlistNode7;
        TRPar trparNode8;
        PReferencesClausel preferencesclauselNode9;
        tconstraintNode2 = (TConstraint)nodeArrayList1.get(0);
        tidentifierNode3 = (TIdentifier)nodeArrayList2.get(0);
        tforeignNode4 = (TForeign)nodeArrayList3.get(0);
        tkeyNode5 = (TKey)nodeArrayList4.get(0);
        tlparNode6 = (TLPar)nodeArrayList5.get(0);
        pidentifierlistNode7 = (PIdentifierList)nodeArrayList6.get(0);
        trparNode8 = (TRPar)nodeArrayList7.get(0);
        preferencesclauselNode9 = (PReferencesClausel)nodeArrayList8.get(0);

        pforeignkeyNode1 = new AForeignKey(tconstraintNode2, tidentifierNode3, tforeignNode4, tkeyNode5, tlparNode6, pidentifierlistNode7, trparNode8, preferencesclauselNode9);
        }
	nodeList.add(pforeignkeyNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new29() /* reduce AAidentifierlist1IdentifierList */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PIdentifierList pidentifierlistNode1;
        {
            // Block
        TIdentifier tidentifierNode2;
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        tidentifierNode2 = (TIdentifier)nodeArrayList1.get(0);
        {
            // Block
        }

        pidentifierlistNode1 = new AIdentifierList(tidentifierNode2, listNode3);
        }
	nodeList.add(pidentifierlistNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new30() /* reduce AAidentifierlist2IdentifierList */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PIdentifierList pidentifierlistNode1;
        {
            // Block
        TIdentifier tidentifierNode2;
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        tidentifierNode2 = (TIdentifier)nodeArrayList1.get(0);
        {
            // Block
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        listNode3 = (LinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pidentifierlistNode1 = new AIdentifierList(tidentifierNode2, listNode4);
        }
	nodeList.add(pidentifierlistNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new31() /* reduce AMoreIdentifier */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PMoreIdentifier pmoreidentifierNode1;
        {
            // Block
        TComma tcommaNode2;
        TIdentifier tidentifierNode3;
        tcommaNode2 = (TComma)nodeArrayList1.get(0);
        tidentifierNode3 = (TIdentifier)nodeArrayList2.get(0);

        pmoreidentifierNode1 = new AMoreIdentifier(tcommaNode2, tidentifierNode3);
        }
	nodeList.add(pmoreidentifierNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new32() /* reduce AReferencesClausel */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PReferencesClausel preferencesclauselNode1;
        {
            // Block
        TReferences treferencesNode2;
        TIdentifier tidentifierNode3;
        TLPar tlparNode4;
        PIdentifierList pidentifierlistNode5;
        TRPar trparNode6;
        treferencesNode2 = (TReferences)nodeArrayList1.get(0);
        tidentifierNode3 = (TIdentifier)nodeArrayList2.get(0);
        tlparNode4 = (TLPar)nodeArrayList3.get(0);
        pidentifierlistNode5 = (PIdentifierList)nodeArrayList4.get(0);
        trparNode6 = (TRPar)nodeArrayList5.get(0);

        preferencesclauselNode1 = new AReferencesClausel(treferencesNode2, tidentifierNode3, tlparNode4, pidentifierlistNode5, trparNode6);
        }
	nodeList.add(preferencesclauselNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new33() /* reduce AAdropclausel1DropClausel */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDropClausel pdropclauselNode1;
        {
            // Block
        TDrop tdropNode2;
        @SuppressWarnings("unused") Object nullNode3 = null;
        TIf tifNode4;
        TExists texistsNode5;
        PIdentifierList pidentifierlistNode6;
        tdropNode2 = (TDrop)nodeArrayList1.get(0);
        tifNode4 = (TIf)nodeArrayList2.get(0);
        texistsNode5 = (TExists)nodeArrayList3.get(0);
        pidentifierlistNode6 = (PIdentifierList)nodeArrayList4.get(0);

        pdropclauselNode1 = new ADropClausel(tdropNode2, null, tifNode4, texistsNode5, pidentifierlistNode6);
        }
	nodeList.add(pdropclauselNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new34() /* reduce AAdropclausel2DropClausel */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDropClausel pdropclauselNode1;
        {
            // Block
        TDrop tdropNode2;
        TTable ttableNode3;
        TIf tifNode4;
        TExists texistsNode5;
        PIdentifierList pidentifierlistNode6;
        tdropNode2 = (TDrop)nodeArrayList1.get(0);
        ttableNode3 = (TTable)nodeArrayList2.get(0);
        tifNode4 = (TIf)nodeArrayList3.get(0);
        texistsNode5 = (TExists)nodeArrayList4.get(0);
        pidentifierlistNode6 = (PIdentifierList)nodeArrayList5.get(0);

        pdropclauselNode1 = new ADropClausel(tdropNode2, ttableNode3, tifNode4, texistsNode5, pidentifierlistNode6);
        }
	nodeList.add(pdropclauselNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new35() /* reduce ATruncateClausel */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTruncateClausel ptruncateclauselNode1;
        {
            // Block
        TTruncate ttruncateNode2;
        TTable ttableNode3;
        TIdentifier tidentifierNode4;
        ttruncateNode2 = (TTruncate)nodeArrayList1.get(0);
        ttableNode3 = (TTable)nodeArrayList2.get(0);
        tidentifierNode4 = (TIdentifier)nodeArrayList3.get(0);

        ptruncateclauselNode1 = new ATruncateClausel(ttruncateNode2, ttableNode3, tidentifierNode4);
        }
	nodeList.add(ptruncateclauselNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new36() /* reduce ADml */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDml pdmlNode1;
        {
            // Block
        PInsertClausel pinsertclauselNode2;
        TSemicolon tsemicolonNode3;
        pinsertclauselNode2 = (PInsertClausel)nodeArrayList1.get(0);
        tsemicolonNode3 = (TSemicolon)nodeArrayList2.get(0);

        pdmlNode1 = new ADml(pinsertclauselNode2, tsemicolonNode3);
        }
	nodeList.add(pdmlNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new37() /* reduce AInsertClausel */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInsertClausel pinsertclauselNode1;
        {
            // Block
        TInsert tinsertNode2;
        TInto tintoNode3;
        TIdentifier tidentifierNode4;
        TLPar tlparNode5;
        PIdentifierList pidentifierlistNode6;
        TRPar trparNode7;
        TValues tvaluesNode8;
        PValueClauselList pvalueclausellistNode9;
        tinsertNode2 = (TInsert)nodeArrayList1.get(0);
        tintoNode3 = (TInto)nodeArrayList2.get(0);
        tidentifierNode4 = (TIdentifier)nodeArrayList3.get(0);
        tlparNode5 = (TLPar)nodeArrayList4.get(0);
        pidentifierlistNode6 = (PIdentifierList)nodeArrayList5.get(0);
        trparNode7 = (TRPar)nodeArrayList6.get(0);
        tvaluesNode8 = (TValues)nodeArrayList7.get(0);
        pvalueclausellistNode9 = (PValueClauselList)nodeArrayList8.get(0);

        pinsertclauselNode1 = new AInsertClausel(tinsertNode2, tintoNode3, tidentifierNode4, tlparNode5, pidentifierlistNode6, trparNode7, tvaluesNode8, pvalueclausellistNode9);
        }
	nodeList.add(pinsertclauselNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new38() /* reduce AAvalueclausellist1ValueClauselList */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PValueClauselList pvalueclausellistNode1;
        {
            // Block
        PValueClausel pvalueclauselNode2;
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        pvalueclauselNode2 = (PValueClausel)nodeArrayList1.get(0);
        {
            // Block
        }

        pvalueclausellistNode1 = new AValueClauselList(pvalueclauselNode2, listNode3);
        }
	nodeList.add(pvalueclausellistNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new39() /* reduce AAvalueclausellist2ValueClauselList */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PValueClauselList pvalueclausellistNode1;
        {
            // Block
        PValueClausel pvalueclauselNode2;
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        pvalueclauselNode2 = (PValueClausel)nodeArrayList1.get(0);
        {
            // Block
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        listNode3 = (LinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pvalueclausellistNode1 = new AValueClauselList(pvalueclauselNode2, listNode4);
        }
	nodeList.add(pvalueclausellistNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new40() /* reduce AValueClausel */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PValueClausel pvalueclauselNode1;
        {
            // Block
        TLPar tlparNode2;
        PValues pvaluesNode3;
        TRPar trparNode4;
        tlparNode2 = (TLPar)nodeArrayList1.get(0);
        pvaluesNode3 = (PValues)nodeArrayList2.get(0);
        trparNode4 = (TRPar)nodeArrayList3.get(0);

        pvalueclauselNode1 = new AValueClausel(tlparNode2, pvaluesNode3, trparNode4);
        }
	nodeList.add(pvalueclauselNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new41() /* reduce AMoreValueClausel */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PMoreValueClausel pmorevalueclauselNode1;
        {
            // Block
        TComma tcommaNode2;
        PValueClausel pvalueclauselNode3;
        tcommaNode2 = (TComma)nodeArrayList1.get(0);
        pvalueclauselNode3 = (PValueClausel)nodeArrayList2.get(0);

        pmorevalueclauselNode1 = new AMoreValueClausel(tcommaNode2, pvalueclauselNode3);
        }
	nodeList.add(pmorevalueclauselNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new42() /* reduce AAvalues1Values */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PValues pvaluesNode1;
        {
            // Block
        PSingleValue psinglevalueNode2;
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        psinglevalueNode2 = (PSingleValue)nodeArrayList1.get(0);
        {
            // Block
        }

        pvaluesNode1 = new AValues(psinglevalueNode2, listNode3);
        }
	nodeList.add(pvaluesNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new43() /* reduce AAvalues2Values */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PValues pvaluesNode1;
        {
            // Block
        PSingleValue psinglevalueNode2;
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        psinglevalueNode2 = (PSingleValue)nodeArrayList1.get(0);
        {
            // Block
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        listNode3 = (LinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pvaluesNode1 = new AValues(psinglevalueNode2, listNode4);
        }
	nodeList.add(pvaluesNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new44() /* reduce AVarSingleValue */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PSingleValue psinglevalueNode1;
        {
            // Block
        TVar tvarNode2;
        tvarNode2 = (TVar)nodeArrayList1.get(0);

        psinglevalueNode1 = new AVarSingleValue(tvarNode2);
        }
	nodeList.add(psinglevalueNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new45() /* reduce AIntSingleValue */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PSingleValue psinglevalueNode1;
        {
            // Block
        TIntegerNumber tintegernumberNode2;
        tintegernumberNode2 = (TIntegerNumber)nodeArrayList1.get(0);

        psinglevalueNode1 = new AIntSingleValue(tintegernumberNode2);
        }
	nodeList.add(psinglevalueNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new46() /* reduce AFloatSingleValue */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PSingleValue psinglevalueNode1;
        {
            // Block
        TFloatingPointNumber tfloatingpointnumberNode2;
        tfloatingpointnumberNode2 = (TFloatingPointNumber)nodeArrayList1.get(0);

        psinglevalueNode1 = new AFloatSingleValue(tfloatingpointnumberNode2);
        }
	nodeList.add(psinglevalueNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new47() /* reduce AStringSingleValue */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PSingleValue psinglevalueNode1;
        {
            // Block
        TStringLiteral tstringliteralNode2;
        tstringliteralNode2 = (TStringLiteral)nodeArrayList1.get(0);

        psinglevalueNode1 = new AStringSingleValue(tstringliteralNode2);
        }
	nodeList.add(psinglevalueNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new48() /* reduce AMoreSingleValue */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PMoreSingleValue pmoresinglevalueNode1;
        {
            // Block
        TComma tcommaNode2;
        PSingleValue psinglevalueNode3;
        tcommaNode2 = (TComma)nodeArrayList1.get(0);
        psinglevalueNode3 = (PSingleValue)nodeArrayList2.get(0);

        pmoresinglevalueNode1 = new AMoreSingleValue(tcommaNode2, psinglevalueNode3);
        }
	nodeList.add(pmoresinglevalueNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new49() /* reduce ATerminal$Sttm */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PSttm psttmNode1;
        psttmNode1 = (PSttm)nodeArrayList1.get(0);
	if(psttmNode1 != null)
	{
	  listNode2.add(psttmNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new50() /* reduce ANonTerminal$Sttm */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PSttm psttmNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        psttmNode2 = (PSttm)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(psttmNode2 != null)
	{
	  listNode3.add(psttmNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new51() /* reduce ATerminal$AdditionColDef */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PAdditionColDef padditioncoldefNode1;
        padditioncoldefNode1 = (PAdditionColDef)nodeArrayList1.get(0);
	if(padditioncoldefNode1 != null)
	{
	  listNode2.add(padditioncoldefNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new52() /* reduce ANonTerminal$AdditionColDef */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PAdditionColDef padditioncoldefNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        padditioncoldefNode2 = (PAdditionColDef)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(padditioncoldefNode2 != null)
	{
	  listNode3.add(padditioncoldefNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new53() /* reduce ATerminal$TableConstraintTail */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PTableConstraintTail ptableconstrainttailNode1;
        ptableconstrainttailNode1 = (PTableConstraintTail)nodeArrayList1.get(0);
	if(ptableconstrainttailNode1 != null)
	{
	  listNode2.add(ptableconstrainttailNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new54() /* reduce ANonTerminal$TableConstraintTail */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PTableConstraintTail ptableconstrainttailNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        ptableconstrainttailNode2 = (PTableConstraintTail)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(ptableconstrainttailNode2 != null)
	{
	  listNode3.add(ptableconstrainttailNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new55() /* reduce ATerminal$ColConstraint */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PColConstraint pcolconstraintNode1;
        pcolconstraintNode1 = (PColConstraint)nodeArrayList1.get(0);
	if(pcolconstraintNode1 != null)
	{
	  listNode2.add(pcolconstraintNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new56() /* reduce ANonTerminal$ColConstraint */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PColConstraint pcolconstraintNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pcolconstraintNode2 = (PColConstraint)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pcolconstraintNode2 != null)
	{
	  listNode3.add(pcolconstraintNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new57() /* reduce ATerminal$IntegerNumber */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        TIntegerNumber tintegernumberNode1;
        tintegernumberNode1 = (TIntegerNumber)nodeArrayList1.get(0);
	if(tintegernumberNode1 != null)
	{
	  listNode2.add(tintegernumberNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new58() /* reduce ANonTerminal$IntegerNumber */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        TIntegerNumber tintegernumberNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        tintegernumberNode2 = (TIntegerNumber)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(tintegernumberNode2 != null)
	{
	  listNode3.add(tintegernumberNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new59() /* reduce ATerminal$MoreIdentifier */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PMoreIdentifier pmoreidentifierNode1;
        pmoreidentifierNode1 = (PMoreIdentifier)nodeArrayList1.get(0);
	if(pmoreidentifierNode1 != null)
	{
	  listNode2.add(pmoreidentifierNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new60() /* reduce ANonTerminal$MoreIdentifier */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PMoreIdentifier pmoreidentifierNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pmoreidentifierNode2 = (PMoreIdentifier)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pmoreidentifierNode2 != null)
	{
	  listNode3.add(pmoreidentifierNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new61() /* reduce ATerminal$MoreValueClausel */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PMoreValueClausel pmorevalueclauselNode1;
        pmorevalueclauselNode1 = (PMoreValueClausel)nodeArrayList1.get(0);
	if(pmorevalueclauselNode1 != null)
	{
	  listNode2.add(pmorevalueclauselNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new62() /* reduce ANonTerminal$MoreValueClausel */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PMoreValueClausel pmorevalueclauselNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pmorevalueclauselNode2 = (PMoreValueClausel)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pmorevalueclauselNode2 != null)
	{
	  listNode3.add(pmorevalueclauselNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new63() /* reduce ATerminal$MoreSingleValue */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PMoreSingleValue pmoresinglevalueNode1;
        pmoresinglevalueNode1 = (PMoreSingleValue)nodeArrayList1.get(0);
	if(pmoresinglevalueNode1 != null)
	{
	  listNode2.add(pmoresinglevalueNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new64() /* reduce ANonTerminal$MoreSingleValue */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PMoreSingleValue pmoresinglevalueNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pmoresinglevalueNode2 = (PMoreSingleValue)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pmoresinglevalueNode2 != null)
	{
	  listNode3.add(pmoresinglevalueNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, ERROR, 0}, {11, SHIFT, 1}, {23, SHIFT, 2}, {24, SHIFT, 3}, {25, SHIFT, 4}, },
			{{-1, ERROR, 1}, {12, SHIFT, 14}, },
			{{-1, ERROR, 2}, {12, SHIFT, 15}, {13, SHIFT, 16}, },
			{{-1, ERROR, 3}, {12, SHIFT, 17}, },
			{{-1, ERROR, 4}, {26, SHIFT, 18}, },
			{{-1, ERROR, 5}, {31, ACCEPT, -1}, },
			{{-1, REDUCE, 49}, },
			{{-1, REDUCE, 1}, },
			{{-1, ERROR, 8}, {3, SHIFT, 19}, },
			{{-1, ERROR, 9}, {3, SHIFT, 20}, },
			{{-1, ERROR, 10}, {3, SHIFT, 21}, },
			{{-1, REDUCE, 2}, },
			{{-1, ERROR, 12}, {3, SHIFT, 22}, },
			{{-1, REDUCE, 0}, {11, SHIFT, 1}, {23, SHIFT, 2}, {24, SHIFT, 3}, {25, SHIFT, 4}, },
			{{-1, ERROR, 14}, {13, SHIFT, 24}, },
			{{-1, ERROR, 15}, {13, SHIFT, 25}, },
			{{-1, ERROR, 16}, {14, SHIFT, 26}, },
			{{-1, ERROR, 17}, {29, SHIFT, 27}, },
			{{-1, ERROR, 18}, {29, SHIFT, 28}, },
			{{-1, REDUCE, 3}, },
			{{-1, REDUCE, 5}, },
			{{-1, REDUCE, 4}, },
			{{-1, REDUCE, 36}, },
			{{-1, REDUCE, 50}, },
			{{-1, ERROR, 24}, {20, SHIFT, 29}, },
			{{-1, ERROR, 25}, {14, SHIFT, 30}, },
			{{-1, ERROR, 26}, {29, SHIFT, 31}, },
			{{-1, REDUCE, 35}, },
			{{-1, ERROR, 28}, {0, SHIFT, 33}, },
			{{-1, ERROR, 29}, {14, SHIFT, 34}, },
			{{-1, ERROR, 30}, {29, SHIFT, 31}, },
			{{-1, REDUCE, 29}, {2, SHIFT, 36}, },
			{{-1, REDUCE, 33}, },
			{{-1, ERROR, 33}, {29, SHIFT, 31}, },
			{{-1, ERROR, 34}, {29, SHIFT, 40}, },
			{{-1, REDUCE, 34}, },
			{{-1, ERROR, 36}, {29, SHIFT, 41}, },
			{{-1, REDUCE, 59}, },
			{{-1, REDUCE, 30}, {2, SHIFT, 36}, },
			{{-1, ERROR, 39}, {1, SHIFT, 43}, },
			{{-1, ERROR, 40}, {0, SHIFT, 44}, },
			{{-1, REDUCE, 31}, },
			{{-1, REDUCE, 60}, },
			{{-1, ERROR, 43}, {27, SHIFT, 46}, },
			{{-1, ERROR, 44}, {29, SHIFT, 47}, },
			{{-1, REDUCE, 6}, },
			{{-1, ERROR, 46}, {0, SHIFT, 49}, },
			{{-1, ERROR, 47}, {6, SHIFT, 52}, {7, SHIFT, 53}, {8, SHIFT, 54}, {9, SHIFT, 55}, {10, SHIFT, 56}, },
			{{-1, ERROR, 48}, {1, SHIFT, 58}, {2, SHIFT, 59}, },
			{{-1, ERROR, 49}, {4, SHIFT, 64}, {5, SHIFT, 65}, {28, SHIFT, 66}, {30, SHIFT, 67}, },
			{{-1, REDUCE, 37}, },
			{{-1, REDUCE, 38}, {2, SHIFT, 70}, },
			{{-1, REDUCE, 13}, },
			{{-1, REDUCE, 14}, },
			{{-1, REDUCE, 15}, },
			{{-1, REDUCE, 16}, },
			{{-1, ERROR, 56}, {0, SHIFT, 73}, },
			{{-1, REDUCE, 11}, {19, SHIFT, 74}, {20, SHIFT, 75}, },
			{{-1, REDUCE, 7}, },
			{{-1, ERROR, 59}, {15, SHIFT, 79}, {29, SHIFT, 47}, },
			{{-1, REDUCE, 51}, },
			{{-1, REDUCE, 53}, },
			{{-1, ERROR, 62}, {1, SHIFT, 84}, {2, SHIFT, 59}, },
			{{-1, ERROR, 63}, {1, SHIFT, 87}, {2, SHIFT, 88}, },
			{{-1, REDUCE, 46}, },
			{{-1, REDUCE, 45}, },
			{{-1, REDUCE, 44}, },
			{{-1, REDUCE, 47}, },
			{{-1, ERROR, 68}, {1, SHIFT, 90}, },
			{{-1, REDUCE, 42}, {2, SHIFT, 91}, },
			{{-1, ERROR, 70}, {0, SHIFT, 49}, },
			{{-1, REDUCE, 61}, },
			{{-1, REDUCE, 39}, {2, SHIFT, 70}, },
			{{-1, ERROR, 73}, {5, SHIFT, 96}, },
			{{-1, REDUCE, 18}, },
			{{-1, ERROR, 75}, {21, SHIFT, 98}, },
			{{-1, REDUCE, 55}, },
			{{-1, REDUCE, 19}, },
			{{-1, REDUCE, 12}, {19, SHIFT, 74}, {20, SHIFT, 75}, },
			{{-1, ERROR, 79}, {29, SHIFT, 100}, },
			{{-1, REDUCE, 21}, },
			{{-1, REDUCE, 26}, },
			{{-1, REDUCE, 24}, },
			{{-1, REDUCE, 25}, },
			{{-1, REDUCE, 8}, },
			{{-1, REDUCE, 52}, },
			{{-1, ERROR, 86}, {1, SHIFT, 101}, {2, SHIFT, 88}, },
			{{-1, REDUCE, 9}, },
			{{-1, ERROR, 88}, {15, SHIFT, 79}, },
			{{-1, REDUCE, 54}, },
			{{-1, REDUCE, 40}, },
			{{-1, ERROR, 91}, {4, SHIFT, 64}, {5, SHIFT, 65}, {28, SHIFT, 66}, {30, SHIFT, 67}, },
			{{-1, REDUCE, 63}, },
			{{-1, REDUCE, 43}, {2, SHIFT, 91}, },
			{{-1, REDUCE, 41}, },
			{{-1, REDUCE, 62}, },
			{{-1, REDUCE, 57}, },
			{{-1, ERROR, 97}, {1, SHIFT, 104}, {5, SHIFT, 105}, },
			{{-1, REDUCE, 20}, },
			{{-1, REDUCE, 56}, },
			{{-1, ERROR, 100}, {16, SHIFT, 106}, {17, SHIFT, 107}, },
			{{-1, REDUCE, 10}, },
			{{-1, REDUCE, 48}, },
			{{-1, REDUCE, 64}, },
			{{-1, REDUCE, 17}, },
			{{-1, REDUCE, 58}, },
			{{-1, ERROR, 106}, {18, SHIFT, 108}, },
			{{-1, ERROR, 107}, {18, SHIFT, 109}, },
			{{-1, ERROR, 108}, {0, SHIFT, 110}, },
			{{-1, ERROR, 109}, {0, SHIFT, 111}, },
			{{-1, ERROR, 110}, {29, SHIFT, 31}, },
			{{-1, ERROR, 111}, {29, SHIFT, 113}, },
			{{-1, ERROR, 112}, {1, SHIFT, 114}, },
			{{-1, ERROR, 113}, {1, SHIFT, 115}, },
			{{-1, ERROR, 114}, {22, SHIFT, 116}, },
			{{-1, REDUCE, 27}, },
			{{-1, ERROR, 116}, {29, SHIFT, 118}, },
			{{-1, REDUCE, 28}, },
			{{-1, ERROR, 118}, {0, SHIFT, 119}, },
			{{-1, ERROR, 119}, {29, SHIFT, 31}, },
			{{-1, ERROR, 120}, {1, SHIFT, 121}, },
			{{-1, REDUCE, 32}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 5}, },
			{{-1, 6}, {13, 23}, },
			{{-1, 7}, },
			{{-1, 8}, },
			{{-1, 45}, },
			{{-1, 48}, {59, 80}, },
			{{-1, 57}, },
			{{-1, 76}, {78, 99}, },
			{{-1, 77}, },
			{{-1, 60}, {62, 85}, },
			{{-1, -1}, },
			{{-1, 81}, },
			{{-1, 61}, {63, 89}, {86, 89}, },
			{{-1, 82}, },
			{{-1, 83}, },
			{{-1, 32}, {30, 35}, {33, 39}, {110, 112}, {119, 120}, },
			{{-1, 37}, {38, 42}, },
			{{-1, 117}, },
			{{-1, 9}, },
			{{-1, 10}, },
			{{-1, 11}, },
			{{-1, 12}, },
			{{-1, 50}, },
			{{-1, 51}, {70, 94}, },
			{{-1, 71}, {72, 95}, },
			{{-1, 68}, },
			{{-1, 69}, {91, 102}, },
			{{-1, 92}, {93, 103}, },
			{{-1, 13}, },
			{{-1, 62}, },
			{{-1, 63}, {62, 86}, },
			{{-1, 78}, },
			{{-1, 97}, },
			{{-1, 38}, },
			{{-1, 72}, },
			{{-1, 93}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: create, drop, truncate, insert",
			"expecting: table",
			"expecting: table, if",
			"expecting: into",
			"expecting: EOF",
			"expecting: create, drop, truncate, insert, EOF",
			"expecting: ';'",
			"expecting: if",
			"expecting: exists",
			"expecting: identifier",
			"expecting: not",
			"expecting: '('",
			"expecting: ')', ',', ';'",
			"expecting: ')'",
			"expecting: values",
			"expecting: integer, bigint, float, timestamp, varchar",
			"expecting: ')', ','",
			"expecting: floating point number, integer number, var, string literal",
			"expecting: ',', ';'",
			"expecting: ')', ',', unique, not",
			"expecting: constraint, identifier",
			"expecting: integer number",
			"expecting: null",
			"expecting: constraint",
			"expecting: ')', integer number",
			"expecting: foreign, primary",
			"expecting: key",
			"expecting: references",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 1, 3, 4, 5, 5, 6, 6, 6, 5, 6, 5, 7, 7, 8, 9, 9, 5, 5, 5, 5, 5, 10, 8, 9, 6, 11, 8, 9, 12, 6, 9, 9, 6, 9, 12, 12, 13, 11, 12, 12, 14, 9, 6, 11, 15, 16, 17, 6, 18, 19, 19, 19, 19, 11, 19, 6, 20, 16, 16, 16, 16, 16, 16, 16, 16, 13, 16, 11, 18, 18, 21, 19, 22, 19, 19, 19, 9, 16, 16, 16, 16, 6, 16, 16, 6, 23, 16, 18, 17, 16, 16, 18, 18, 24, 24, 19, 19, 25, 6, 16, 16, 19, 24, 26, 26, 11, 11, 9, 9, 13, 13, 27, 16, 9, 16, 11, 9, 13, 16, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            Parser.actionTable = new int[length][][];
            for(int i = 0; i < Parser.actionTable.length; i++)
            {
                length = s.readInt();
                Parser.actionTable[i] = new int[length][3];
                for(int j = 0; j < Parser.actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    Parser.actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
