/* This file was generated by SableCC (http://www.sablecc.org/). */

package mysqlgrm.parser;

import mysqlgrm.node.*;
import mysqlgrm.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTLPar(@SuppressWarnings("unused") TLPar node)
    {
        this.index = 0;
    }

    @Override
    public void caseTRPar(@SuppressWarnings("unused") TRPar node)
    {
        this.index = 1;
    }

    @Override
    public void caseTComma(@SuppressWarnings("unused") TComma node)
    {
        this.index = 2;
    }

    @Override
    public void caseTSemicolon(@SuppressWarnings("unused") TSemicolon node)
    {
        this.index = 3;
    }

    @Override
    public void caseTFloatingPointNumber(@SuppressWarnings("unused") TFloatingPointNumber node)
    {
        this.index = 4;
    }

    @Override
    public void caseTIntegerNumber(@SuppressWarnings("unused") TIntegerNumber node)
    {
        this.index = 5;
    }

    @Override
    public void caseTInteger(@SuppressWarnings("unused") TInteger node)
    {
        this.index = 6;
    }

    @Override
    public void caseTBigint(@SuppressWarnings("unused") TBigint node)
    {
        this.index = 7;
    }

    @Override
    public void caseTFloat(@SuppressWarnings("unused") TFloat node)
    {
        this.index = 8;
    }

    @Override
    public void caseTTimestamp(@SuppressWarnings("unused") TTimestamp node)
    {
        this.index = 9;
    }

    @Override
    public void caseTVarchar(@SuppressWarnings("unused") TVarchar node)
    {
        this.index = 10;
    }

    @Override
    public void caseTCreate(@SuppressWarnings("unused") TCreate node)
    {
        this.index = 11;
    }

    @Override
    public void caseTTable(@SuppressWarnings("unused") TTable node)
    {
        this.index = 12;
    }

    @Override
    public void caseTIf(@SuppressWarnings("unused") TIf node)
    {
        this.index = 13;
    }

    @Override
    public void caseTExists(@SuppressWarnings("unused") TExists node)
    {
        this.index = 14;
    }

    @Override
    public void caseTConstraint(@SuppressWarnings("unused") TConstraint node)
    {
        this.index = 15;
    }

    @Override
    public void caseTForeign(@SuppressWarnings("unused") TForeign node)
    {
        this.index = 16;
    }

    @Override
    public void caseTPrimary(@SuppressWarnings("unused") TPrimary node)
    {
        this.index = 17;
    }

    @Override
    public void caseTKey(@SuppressWarnings("unused") TKey node)
    {
        this.index = 18;
    }

    @Override
    public void caseTUnique(@SuppressWarnings("unused") TUnique node)
    {
        this.index = 19;
    }

    @Override
    public void caseTNot(@SuppressWarnings("unused") TNot node)
    {
        this.index = 20;
    }

    @Override
    public void caseTNull(@SuppressWarnings("unused") TNull node)
    {
        this.index = 21;
    }

    @Override
    public void caseTReferences(@SuppressWarnings("unused") TReferences node)
    {
        this.index = 22;
    }

    @Override
    public void caseTDrop(@SuppressWarnings("unused") TDrop node)
    {
        this.index = 23;
    }

    @Override
    public void caseTTruncate(@SuppressWarnings("unused") TTruncate node)
    {
        this.index = 24;
    }

    @Override
    public void caseTInsert(@SuppressWarnings("unused") TInsert node)
    {
        this.index = 25;
    }

    @Override
    public void caseTInto(@SuppressWarnings("unused") TInto node)
    {
        this.index = 26;
    }

    @Override
    public void caseTValues(@SuppressWarnings("unused") TValues node)
    {
        this.index = 27;
    }

    @Override
    public void caseTVar(@SuppressWarnings("unused") TVar node)
    {
        this.index = 28;
    }

    @Override
    public void caseTIdentifier(@SuppressWarnings("unused") TIdentifier node)
    {
        this.index = 29;
    }

    @Override
    public void caseTStringLiteral(@SuppressWarnings("unused") TStringLiteral node)
    {
        this.index = 30;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 31;
    }
}
